SELECT
    (doc ->> '_id')::text AS doc_id,
    (doc ->> '_rev')::text AS doc_rev,
    (doc ->> 'type')::text AS doc_type,
    (doc ->> 'df_complete')::text AS doc_df_complete,
    (doc ->> 'df_submitted')::text AS doc_df_submitted,
    (doc ->> 'df_parent_complete')::text AS doc_df_parent_complete,
    (doc ->> 'event_ident')::text AS doc_event_ident,
    (doc ->> 'mform_event')::text AS doc_mform_event,
    (doc ->> 'parent_ident')::text AS doc_parent_ident,
    (doc -> 'created_scope' ->> 'user_role')::text AS created_scope_user_role,
    (doc -> 'modified_scope' ->> 'user_role')::text AS modified_scope_user_role,
    (doc ->> 'mform_id')::text AS mform_id,
    (doc ->> 'fform_id')::text AS form_id,
    (doc ->> 'ident')::text AS case_unique_id,
    (doc ->> 'created_username')::text AS created_username,
    (doc ->> 'created_timestamp')::text AS created_timestamp,
    (doc ->> 'modified_username')::text AS modified_username,
    (doc ->> 'modified_timestamp')::text AS modified_timestamp,
    (doc -> 'location' ->> 'accuracy')::text AS location_accuracy,
    (doc -> 'location' ->> 'latitude')::text AS location_latitude,
    (doc -> 'location' ->> 'longitude')::text AS location_longitude,
    -- (doc -> 'DFields' -> 'values' -> 'syndrome' ->> 'df_value')::text AS syndrome,
    (doc -> 'DFields' -> 'values' -> 'disease' ->> 'df_value')::text AS disease,
    (doc -> 'DFields' -> 'values' -> 'EPID' ->> 'df_value')::text AS epid,
    (doc -> 'DFields' -> 'values' -> 'date_of_investigation' ->> 'df_value')::text AS date_of_investigation,
    (doc -> 'DFields' -> 'values' -> 'location_of_investigation' ->> 'df_value')::text AS location_of_investigation,
    (doc -> 'DFields' -> 'values' -> 'location_of_investigation_other' ->> 'df_value')::text AS location_of_investigation_other,
    (doc -> 'DFields' -> 'values' -> 'type_of_case' ->> 'df_value')::text AS type_of_case,
    -- (doc -> 'DFields' -> 'values' -> 'unique_id_of_case' ->> 'df_value')::text AS unique_id_of_case,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'family' ->> 'df_value')::text AS family,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'given' ->> 'df_value')::text AS given,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'sex' ->> 'df_value')::text AS sex,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'date_of_birth' ->> 'df_value')::text AS date_of_birth,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'age_years' ->> 'df_value')::text AS age_years,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'age_months' ->> 'df_value')::text AS age_months,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'age_days' ->> 'df_value')::text AS age_days,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'case_is_pregnant' ->> 'df_value')::text AS case_is_pregnant,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'phone_number' ->> 'df_value')::text AS phone_number,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'occupation' ->> 'df_value')::text AS occupation,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'occupation_other' ->> 'df_value')::text AS occupation_other,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'title_residence' ->> 'df_value')::text AS title_residence,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'type_of_residence' ->> 'df_value')::text AS type_of_residence,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'country' ->> 'df_value')::text AS country,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'county' ->> 'df_value')::text AS county,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'subcounty' ->> 'df_value')::text AS subcounty,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'ward' ->> 'df_value')::text AS ward,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'town_village_camp' ->> 'df_value')::text AS town_village_camp,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'landmark' ->> 'df_value')::text AS landmark,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'marital_status' ->> 'df_value')::text AS marital_status,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'level_of_education' ->> 'df_value')::text AS level_of_education,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'case_has_insurance_cover' ->> 'df_value')::text AS case_has_insurance_cover,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'title_parent_guradian' ->> 'df_value')::text AS title_parent_guradian,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'guardian_family_name' ->> 'df_value')::text AS guardian_family_name,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'guardian_given_name' ->> 'df_value')::text AS guardian_given_name,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'guardian_phone_number' ->> 'df_value')::text AS guardian_phone_number,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'title_respondent' ->> 'df_value')::text AS title_respondent,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'respondent' ->> 'df_value')::text AS respondent,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'respondent_family_name' ->> 'df_value')::text AS respondent_family_name,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'respondent_given_name' ->> 'df_value')::text AS respondent_given_name,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'respondent_address' ->> 'df_value')::text AS respondent_address,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'respondent_phone_number' ->> 'df_value')::text AS respondent_phone_number,
    (doc -> 'DForms' -> 'case_demographics' -> 0 -> 'DFields' -> 'values' -> 'respondent_relationship' ->> 'df_value')::text AS respondent_relationship,
    (doc -> 'DForms' -> 'clinical_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'symptoms' ->> 'df_value')::text AS symptoms,
    (doc -> 'DForms' -> 'clinical_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'symptoms_other' ->> 'df_value')::text AS symptoms_other,
    (doc -> 'DForms' -> 'clinical_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'fever_temperature' ->> 'df_value')::text AS fever_temperature,
    (doc -> 'DForms' -> 'clinical_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'locations_of_lymphadenopathy' ->> 'df_value')::text AS locations_of_lymphadenopathy,
    (doc -> 'DForms' -> 'clinical_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'date_of_onset' ->> 'df_value')::text AS date_of_onset,
    (doc -> 'DForms' -> 'clinical_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'start_location_of_rash' ->> 'df_value')::text AS start_location_of_rash,
    (doc -> 'DForms' -> 'clinical_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'start_location_of_rash_other' ->> 'df_value')::text AS start_location_of_rash_other,
    (doc -> 'DForms' -> 'clinical_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'spread_location_of_rash' ->> 'df_value')::text AS spread_location_of_rash,
    (doc -> 'DForms' -> 'clinical_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'spread_location_of_rash_other' ->> 'df_value')::text AS spread_location_of_rash_other,
    (doc -> 'DForms' -> 'clinical_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'number_of_lesions' ->> 'df_value')::text AS number_of_lesions,
    (doc -> 'DForms' -> 'clinical_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'development_of_rash' ->> 'df_value')::text AS development_of_rash,
    (doc -> 'DForms' -> 'clinical_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'distribution_of_rash' ->> 'df_value')::text AS distribution_of_rash,
    (doc -> 'DForms' -> 'clinical_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'history_of_immunosuppressive_conditions' ->> 'df_value')::text AS history_of_immunosuppressive_conditions,
    (doc -> 'DForms' -> 'clinical_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'hiv_positive' ->> 'df_value')::text AS hiv_positive,
    (doc -> 'DForms' -> 'clinical_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'date_of_hiv_diagnosis' ->> 'df_value')::text AS date_of_hiv_diagnosis,
    (doc -> 'DForms' -> 'clinical_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'patient_on_art' ->> 'df_value')::text AS patient_on_art,
    (doc -> 'DForms' -> 'clinical_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'history_of_skin_disease' ->> 'df_value')::text AS history_of_skin_disease,
    (doc -> 'DForms' -> 'clinical_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'recently_given_birth' ->> 'df_value')::text AS recently_given_birth,
    (doc -> 'DForms' -> 'clinical_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'baby_is_symptomatic' ->> 'df_value')::text AS baby_is_symptomatic,
    (doc -> 'DForms' -> 'clinical_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'case_is_breatfeeding' ->> 'df_value')::text AS case_is_breatfeeding,
    (doc -> 'DForms' -> 'clinical_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'case_was_breastfeeding_three_weeks_prior_to_illness' ->> 'df_value')::text AS case_was_breastfeeding_three_weeks_prior_to_illness,
    -- (doc -> 'DForms' -> 'clinical_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'title_clinical_care' ->> 'df_value')::text AS title_clinical_care,
    (doc -> 'DForms' -> 'clinical_care_mpox' -> 0 -> 'DFields' -> 'values' -> 'type_of_care' ->> 'df_value')::text AS type_of_care,
    -- (doc -> 'DForms' -> 'clinical_care_mpox' -> 0 -> 'DFields' -> 'values' -> 'case_is_isolated' ->> 'df_value')::text AS case_is_isolated,
    (doc -> 'DForms' -> 'clinical_care_mpox' -> 0 -> 'DFields' -> 'values' -> 'name_of_health_facility' ->> 'df_value')::text AS health_facility_name,
    (doc -> 'DForms' -> 'clinical_care_mpox' -> 0 -> 'DFields' -> 'values' -> 'reason_for_hospitalization' ->> 'df_value')::text AS reason_for_hospitalization,
    (doc -> 'DForms' -> 'clinical_care_mpox' -> 0 -> 'DFields' -> 'values' -> 'reason_for_hospitalization_other' ->> 'df_value')::text AS reason_for_hospitalization_other,
    (doc -> 'DForms' -> 'clinical_care_mpox' -> 0 -> 'DFields' -> 'values' -> 'date_of_admission' ->> 'df_value')::text AS date_of_admission,
    (doc -> 'DForms' -> 'clinical_care_mpox' -> 0 -> 'DFields' -> 'values' -> 'inpatient_number' ->> 'df_value')::text AS inpatient_number,
    -- (doc -> 'DForms' -> 'clinical_care_mpox' -> 0 -> 'DFields' -> 'values' -> 'date_first_seen_at_facility' ->> 'df_value')::text AS date_first_seen_at_facility,
    (doc -> 'DForms' -> 'clinical_care_mpox' -> 0 -> 'DFields' -> 'values' -> 'outpatient_number' ->> 'df_value')::text AS outpatient_number,
    (doc -> 'DForms' -> 'clinical_care_mpox' -> 0 -> 'DFields' -> 'values' -> 'treatment_given' ->> 'df_value')::text AS treatment_given,
    (doc -> 'DForms' -> 'clinical_care_mpox' -> 0 -> 'DFields' -> 'values' -> 'treatment_given_other' ->> 'df_value')::text AS treatment_given_other,
    (doc -> 'DForms' -> 'clinical_care_mpox' -> 0 -> 'DFields' -> 'values' -> 'outcome_of_case' ->> 'df_value')::text AS outcome_of_patient,
    (doc -> 'DForms' -> 'clinical_care_mpox' -> 0 -> 'DFields' -> 'values' -> 'status_of_case' ->> 'df_value')::text AS status_of_patient,
    (doc -> 'DForms' -> 'clinical_care_mpox' -> 0 -> 'DFields' -> 'values' -> 'date_of_discharge' ->> 'df_value')::text AS date_of_discharge,
    (doc -> 'DForms' -> 'clinical_care_mpox' -> 0 -> 'DFields' -> 'values' -> 'date_of_death' ->> 'df_value')::text AS date_of_death,
    (doc -> 'DForms' -> 'clinical_care_mpox' -> 0 -> 'DFields' -> 'values' -> 'place_of_death' ->> 'df_value')::text AS place_of_death,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'food_name' ->> 'df_value')::text AS food_name,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'food_source' ->> 'df_value')::text AS food_source,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'food_consumption_date' ->> 'df_value')::text AS food_consumption_date,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'food_participants_count' ->> 'df_value')::text AS food_participants_count,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'food_affected_participants_count' ->> 'df_value')::text AS food_affected_participants_count,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'water_sources' ->> 'df_value')::text AS water_sources,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'water_sources_other' ->> 'df_value')::text AS water_sources_other,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'toilet_types' ->> 'df_value')::text AS toilet_types,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'toilet_types_other' ->> 'df_value')::text AS toilet_types_other,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'travel_origin_country' ->> 'df_value')::text AS travel_origin_country,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'travel_origin_city' ->> 'df_value')::text AS travel_origin_city,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'travel_departure_date' ->> 'df_value')::text AS travel_departure_date,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'travel_destination_country' ->> 'df_value')::text AS travel_destination_country,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'travel_destination_city' ->> 'df_value')::text AS travel_destination_city,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'travel_arrival_date' ->> 'df_value')::text AS travel_arrival_date,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'animal_exposure_location' ->> 'df_value')::text AS animal_exposure_location,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'type_of_exposure' ->> 'df_value')::text AS type_of_exposure,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'type_of_case_contact' ->> 'df_value')::text AS type_of_contact,
    -- (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'contact_was_symptomatic' ->> 'df_value')::text AS contact_was_symptomatic,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'case_was_symptomatic_during_contact' ->> 'df_value')::text AS contact_was_symptomatic,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'date_of_contact' ->> 'df_value')::text AS date_of_contact,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'frequency_of_contact' ->> 'df_value')::text AS frequency_of_contact,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'duration_of_contact' ->> 'df_value')::text AS duration_of_contact,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'location_of_contact' ->> 'df_value')::text AS location_of_contact,
    -- (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'location_of_contact_other' ->> 'df_value')::text AS location_of_contact_other,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'relationship' ->> 'df_value')::text AS relationship_of_contact,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'relationship_other' ->> 'df_value')::text AS relationship_of_contact_other,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'title_ppe' ->> 'df_value')::text AS title_ppe,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'case_was_wearing_ppe' ->> 'df_value')::text AS case_was_wearing_ppe,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'ppe_items_worn' ->> 'df_value')::text AS ppe_items_worn,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'ppe_breach' ->> 'df_value')::text AS ppe_breach,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'hand_hygiene_before_wearing_ppe' ->> 'df_value')::text AS hand_hygiene_before_wearing_ppe,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'hand_hygiene_after_wearing_ppe' ->> 'df_value')::text AS hand_hygiene_after_wearing_ppe,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'animal_species' ->> 'df_value')::text AS animal_species,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'animal_species_other' ->> 'df_value')::text AS animal_species_other,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'animal_exposure' ->> 'df_value')::text AS animal_exposure,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'animal_exposure_other' ->> 'df_value')::text AS animal_exposure_other,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'animal_exposure_date' ->> 'df_value')::text AS date_of_exposure,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'case_was_ill' ->> 'df_value')::text AS case_was_ill,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'description_of_event' ->> 'df_value')::text AS description_of_event,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'location_of_event' ->> 'df_value')::text AS location_of_event,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'date_of_event' ->> 'df_value')::text AS date_of_event,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'description_of_illness' ->> 'df_value')::text AS description_of_illness,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'type_of_direct_contact' ->> 'df_value')::text AS type_of_direct_contact,
    (doc -> 'DForms' -> 'case_exposure' -> 0 -> 'DFields' -> 'values' -> 'type_of_direct_contact_other' ->> 'df_value')::text AS type_of_direct_contact_other,
    (doc -> 'DForms' -> 'laboratory_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'laboratory_samples_were_collected' ->> 'df_value')::text AS samples_were_collected,
    (doc -> 'DForms' -> 'laboratory_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'laboratory_samples_collected' ->> 'df_value')::text AS samples_collected,
    (doc -> 'DForms' -> 'laboratory_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'laboratory_samples_collected_other' ->> 'df_value')::text AS samples_collected_other,
    (doc -> 'DForms' -> 'laboratory_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'date_of_sample_collection' ->> 'df_value')::text AS date_of_sample_collection,
    (doc -> 'DForms' -> 'laboratory_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'laboratory_tests' ->> 'df_value')::text AS tests,
    (doc -> 'DForms' -> 'laboratory_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'laboratory_test_other' ->> 'df_value')::text AS test_other,
    (doc -> 'DForms' -> 'laboratory_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'result_of_laboratory_test' ->> 'df_value')::text AS result_of_laboratory_test,
    (doc -> 'DForms' -> 'laboratory_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'date_of_laboratory_testing_results' ->> 'df_value')::text AS date_of_laboratory_testing_results,
    (doc -> 'DForms' -> 'laboratory_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'laboratory_facility_name' ->> 'df_value')::text AS facility_name,
    (doc -> 'DForms' -> 'laboratory_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'laboratory_facility_name_other' ->> 'df_value')::text AS facility_name_other,
    (doc -> 'DForms' -> 'laboratory_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'clade_of_mpox' ->> 'df_value')::text AS clade_of_mpox,
    (doc -> 'DForms' -> 'contact_follow_up' -> 0 -> 'DFields' -> 'values' -> 'day_of_follow_up' ->> 'df_value')::text AS day_of_follow_up,
    (doc -> 'DForms' -> 'contact_follow_up' -> 0 -> 'DFields' -> 'values' -> 'date_of_follow_up' ->> 'df_value')::text AS date_of_follow_up,
    (doc -> 'DForms' -> 'contact_follow_up' -> 0 -> 'DFields' -> 'values' -> 'contact_is_symptomatic' ->> 'df_value')::text AS contact_is_symptomatic,
    (doc -> 'DForms' -> 'vaccination_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'smallpox_mpox_vaccine_received' ->> 'df_value')::text AS smallpox_mpox_vaccine_received,
    (doc -> 'DForms' -> 'vaccination_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'number_of_doses' ->> 'df_value')::text AS number_of_doses,
    -- (doc -> 'DForms' -> 'vaccination_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'date_of_first_dose' ->> 'df_value')::text AS date_of_first_dose,
    (doc -> 'DForms' -> 'vaccination_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'date_of_last_dose' ->> 'df_value')::text AS date_of_last_dose,
    (doc -> 'DForms' -> 'vaccination_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'brand_of_vaccine' ->> 'df_value')::text AS brand_of_vaccine,
    (doc -> 'DForms' -> 'vaccination_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'brand_of_vaccine_other' ->> 'df_value')::text AS brand_of_vaccine_other,
    (doc -> 'DForms' -> 'vaccination_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'route_of_admission' ->> 'df_value')::text AS route_of_admission,
    (doc -> 'DForms' -> 'vaccination_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'route_of_admission_other' ->> 'df_value')::text AS route_of_admission_other,
    (doc -> 'DForms' -> 'vaccination_information_monkey_pox' -> 0 -> 'DFields' -> 'values' -> 'reason_for_vaccination' ->> 'df_value')::text AS reason_for_vaccination
FROM {{ source('couchdb', 'couchdb') }}
WHERE
    (doc ->> 'type')::text = 'dform'
-- AND
    -- (doc -> 'DFields' -> 'values' -> 'disease' ->> 'df_value')::text = 'Monkey Pox'
AND
    (doc ->> 'mform_id')::text = '1cb1ce40-52f3-11ef-b3d2-414aed6a4e0a'
AND
    (doc -> 'ident') IS NOT NULL
