SELECT
    (doc ->> '_id')::text AS doc_id,
    (doc ->> '_rev')::text AS doc_rev,
    (doc ->> 'type')::text AS doc_type,
    (doc ->> 'df_complete')::text AS df_complete,
    (doc ->> 'df_submitted')::text AS df_submitted,
    (doc ->> 'df_parent_complete')::text AS df_parent_complete,
    (doc ->> 'event_ident')::text AS event_ident,
    (doc ->> 'mform_event')::text AS mform_event,
    (doc ->> 'parent_ident')::text AS parent_ident,
    (doc -> 'created_scope' ->> 'user_role')::text AS created_role,
    (doc -> 'modified_scope' ->> 'user_role')::text AS modified_role,
    (doc ->> 'mform_id')::text AS mform_id,
    (doc ->> 'fform_id')::text AS form_id,
    (doc ->> 'ident')::text AS case_unique_id,
    (doc ->> 'created_username')::text AS created_username,
    (doc ->> 'created_timestamp')::text AS created_timestamp,
    (doc ->> 'modified_username')::text AS modified_username,
    (doc ->> 'modified_timestamp')::text AS modified_timestamp,
    (doc -> 'location' ->> 'accuracy')::text AS location_accuracy,
    (doc -> 'location' ->> 'latitude')::text AS location_latitude,
    (doc -> 'location' ->> 'longitude')::text AS location_longitude,
    (doc -> 'DFields' -> 'values' -> 'name_of_the_validator' ->> 'df_value')::text AS name_of_the_validator,
    (doc -> 'DFields' -> 'values' -> 'phone_number' ->> 'df_value')::text AS validator_phone_number,
    (doc -> 'DFields' -> 'values' -> 'date_of_assessment' ->> 'df_value')::text AS date_of_assessment,
    (doc -> 'DFields' -> 'values' -> 'county' ->> 'df_value')::text AS county,
    (doc -> 'DForms' -> 'mvd_preparedness_ipc' -> 0 -> 'DFields' -> 'values' -> 'at_least_eighty_percent_of_high_risk_subcounties_have_staff_trained_and_available_for_managing_vhf_mvd_ cases' ->> 'df_value')::text AS ipc_staff_trained_vhf_cases,
    (doc -> 'DForms' -> 'mvd_preparedness_ipc' -> 0 -> 'DFields' -> 'values' -> 'at_least_eighty_percent_of_healthcare_facilities_in_high_risk_subcounties_have_an_ipc_triage_system' ->> 'df_value')::text AS ipc_triage_system,
    (doc -> 'DForms' -> 'mvd_preparedness_ipc' -> 0 -> 'DFields' -> 'values' -> 'at_least_80percent_of_health_workers_in_high_risk_subcounties_are_trained_in_ipc' ->> 'df_value')::text AS ipc_hw_trained_80percent,
    (doc -> 'DForms' -> 'mvd_preparedness_ipc' -> 0 -> 'DFields' -> 'values' -> 'at_least_eighty_percent_of_healthcare_facilities_in_high_risk_subcounties_have_infection_prevention_and_control_guidelines_and_sops' ->> 'df_value')::text AS ipc_guidelines_sops,
    (doc -> 'DForms' -> 'mvd_preparedness_ipc' -> 0 -> 'DFields' -> 'values' -> 'community_volunteers_have_been_identified_and_trained_in_the_preparation_of_disinfection_solutions_and_their_use_in_at_least_80percent_of_high_risk_subcounties' ->> 'df_value')::text AS ipc_community_volunteers_disinfection,
    (doc -> 'DForms' -> 'mvd_preparedness_ipc' -> 0 -> 'DFields' -> 'values' -> 'teams_have_been_identified_and_trained_to_conduct_household_disinfection_in_at_least_eighty_percent_of_high_risk_subcounties' ->> 'df_value')::text AS ipc_teams_household_disinfection,
    (doc -> 'DForms' -> 'mvd_preparedness_ipc' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_a_protocol_for_safe_and_dignified_burial_of_vhf_mvd_related_deaths_including_disinfection_transport_and_safe_and_dignified_burial' ->> 'df_value')::text AS ipc_safe_dignified_burial,
    (doc -> 'DForms' -> 'mvd_preparedness_poe' -> 0 -> 'DFields' -> 'values' -> 'county_has_a_contingency_plan_for_official_high_risk_poes' ->> 'df_value')::text AS poe_contingency_plan,
    (doc -> 'DForms' -> 'mvd_preparedness_poe' -> 0 -> 'DFields' -> 'values' -> 'all_designated_and_undesignated_poe_have_faciltiies_for_medical_examination_ of_suspected_cases' ->> 'df_value')::text AS poe_medical_examination_facilities,
    (doc -> 'DForms' -> 'mvd_preparedness_poe' -> 0 -> 'DFields' -> 'values' -> 'all_designated_and_undesignated_poe_have_mechanism_for_temperature_monitoring_screening_for_incoming_travellers_availability_of_thermo_scanners' ->> 'df_value')::text AS poe_mechanism_temp_monitoring,
    (doc -> 'DForms' -> 'mvd_preparedness_poe' -> 0 -> 'DFields' -> 'values' -> 'all_designated_and_undesignated_points_of_entries_have_facilities_for_isolation_and_quarantine_of_suspected_cases' ->> 'df_value')::text AS poe_isolation_quarantine_facilities,
    (doc -> 'DForms' -> 'mvd_preparedness_poe' -> 0 -> 'DFields' -> 'values' -> 'all_points_of_entries_are_linked_to_emeregncy_ambulance_service_at_all_times' ->> 'df_value')::text AS poe_ambulance_service_link,
    (doc -> 'DForms' -> 'mvd_preparedness_poe' -> 0 -> 'DFields' -> 'values' -> 'all_point_of_entries_are_linked_to_an_intergrated_travellers_health_surveillance_system' ->> 'df_value')::text AS poe_integrated_surveillance_system,
    (doc -> 'DForms' -> 'mvd_preparedness_poe' -> 0 -> 'DFields' -> 'values' -> 'at_least_eighty_percent_of_official_poes_have_health_staff_capable_of_managing_vhf_cases ' ->> 'df_value')::text AS poe_staff_manage_vhf,
    (doc -> 'DForms' -> 'mvd_preparedness_poe' -> 0 -> 'DFields' -> 'values' -> 'all_point_of_entries_have_functional_handwashing_facilities_with_soap_and_water' ->> 'df_value')::text AS poe_functional_handwashing,
    (doc -> 'DForms' -> 'mvd_preparedness_poe' -> 0 -> 'DFields' -> 'values' -> 'posters_and_leaflets_for_traveller_health_education_are_made_available_in_all_point_of_entries_translated_into_local_and_traveller_languages' ->> 'df_value')::text AS poe_posters_leaflets,
    (doc -> 'DForms' -> 'mvd_preparedness_rrt' -> 0 -> 'DFields' -> 'values' -> 'county_has_trained_multidisciplinary_rrts_with_clear_terms_of_reference' ->> 'df_value')::text AS rrt_county_trained_multidisciplinary,
    (doc -> 'DForms' -> 'mvd_preparedness_rrt' -> 0 -> 'DFields' -> 'values' -> 'multidisciplinary_rapid_response_teams_rrts_have_been_established_and_trained_in_highrisk_subcounties' ->> 'df_value')::text AS rrt_established_in_highrisk_sc,
    (doc -> 'DForms' -> 'mvd_preparedness_rrt' -> 0 -> 'DFields' -> 'values' -> 'trained_rrts_have_adequate_equipment_and_logistics_to_enable_them_to_be_deployed_within_24_hours_of_notification_of_mvd_alert_in_each_subcounty_at_risk' ->> 'df_value')::text AS rrt_equipment_logistics_24hr,
    (doc -> 'DForms' -> 'mvd_preparedness_rrt' -> 0 -> 'DFields' -> 'values' -> 'all_rrts_have_sops_and_guidelines_for_investigation_risk_assessment_and_case_management' ->> 'df_value')::text AS rrt_sops_guidelines,
    (doc -> 'DForms' -> 'mvd_preparedness_wash' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_prepositioned_kits_and_other_wash_essential_commdoties_for_vhf_mvd_response_in_at_least_80percent_of_high_risk_subcounties' ->> 'df_value')::text AS wash_prepositioned_kits_80percent,
    (doc -> 'DForms' -> 'mvd_preparedness_wash' -> 0 -> 'DFields' -> 'values' -> 'eighty_percent_of_ health_facilities_have_access_to_a_standard_incinerator' ->> 'df_value')::text AS wash_80percent_hf_incinerator,
    (doc -> 'DForms' -> 'mvd_preparedness_wash' -> 0 -> 'DFields' -> 'values' -> 'eighty_percent_of_the_faciltities_have_proper_secure_waste_zones_in_place' ->> 'df_value')::text AS wash_secure_waste_zones,
    (doc -> 'DForms' -> 'mvd_preparedness_wash' -> 0 -> 'DFields' -> 'values' -> 'eighty_percent_of_health_facilities_have_acess_to_safe_clean_portable_water ' ->> 'df_value')::text AS wash_80percent_water_access,
    (doc -> 'DForms' -> 'mvd_preparedness_wash' -> 0 -> 'DFields' -> 'values' -> 'eighty_percent_of_health_facilities_in_high_risk_subcounties_have_functioning_clinical_medical_waste_management_systems ' ->> 'df_value')::text AS wash_medical_waste_management,
    (doc -> 'DForms' -> 'mvd_preparedness_overall' -> 0 -> 'DFields' -> 'values' -> 'overall_comment' ->> 'df_value')::text AS overall_comment,
    (doc -> 'DForms' -> 'mvd_preparedness_financing' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_a_contigency_emergency_fund_in_place_and_is_easly_accessible' ->> 'df_value')::text AS financing_contingency_emergency_fund,
    (doc -> 'DForms' -> 'mvd_preparedness_laboratory' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_a_pre_positioned_stock_of_mvd_vh_rdts_and_appropriate_sample_transport_media_in_eighty_percent_of_the_hotspots' ->> 'df_value')::text AS lab_pre_positioned_stock,
    (doc -> 'DForms' -> 'mvd_preparedness_laboratory' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_the_capacity_for_reverse_transcriptase_pcr_and_with_adequate_biosafety_levels_for_mvd_diagnosis' ->> 'df_value')::text AS lab_reverse_transcriptase_pcr_capacity,
    (doc -> 'DForms' -> 'mvd_preparedness_laboratory' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_sops_for_collection_packaging_and_transport_of_samples' ->> 'df_value')::text AS lab_sops_collection_transport,
    (doc -> 'DForms' -> 'mvd_preparedness_laboratory' -> 0 -> 'DFields' -> 'values' -> 'at_least_eighty_percent_of_high_risk_subcounties_have_sops_for_sample_collection_packaging_and_transport' ->> 'df_value')::text AS lab_sops_subcounties_80percent,
    (doc -> 'DForms' -> 'mvd_preparedness_laboratory' -> 0 -> 'DFields' -> 'values' -> 'at_least_percent_percent_of_high_risk_subcounties_have_staff_trained_in_sample_collection_packaging_and_transport' ->> 'df_value')::text AS lab_staff_trained_sample_transport,
    (doc -> 'DForms' -> 'mvd_preparedness_laboratory' -> 0 -> 'DFields' -> 'values' -> 'trained_staff_on_safety_and_ipc_procedures_are_present_on_the_field_for_sample_collection_packaging_labelling_transfer_and_transport' ->> 'df_value')::text AS lab_trained_staff_safety_ipc,
    (doc -> 'DForms' -> 'mvd_preparedness_laboratory' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_a_functional_system_for_reporting_laboratory_results_to_stakeholders_health_workers_and_health_authorities' ->> 'df_value')::text AS lab_functional_reporting_system,
    (doc -> 'DForms' -> 'mvd_preparedness_laboratory' -> 0 -> 'DFields' -> 'values' -> 'county_provides_capacity_for_sequencing_of_circulating_mvd' ->> 'df_value')::text AS lab_capacity_for_sequencing,
    (doc -> 'DForms' -> 'mvd_preparedness_vaccination' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_established_procedures_for_importing_and_clearing_vaccines_at_the_point_of_entry' ->> 'df_value')::text AS vaccination_import_clearing_procedures,
    (doc -> 'DForms' -> 'mvd_preparedness_vaccination' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_developed_a_vaccination_strategy ' ->> 'df_value')::text AS vaccination_strategy_developed,
    (doc -> 'DForms' -> 'mvd_preparedness_vaccination' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_initiated_preventive_vaccination_in_at_least_eighty_percent_of_hotspots' ->> 'df_value')::text AS vaccination_initiated_80percent_hotspots,
    (doc -> 'DForms' -> 'mvd_preparedness_vaccination' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_identified_prospective_technical_and_logistics_partners_for_mass_immunisation_at_the_national_level__including_campaign_implementation,_monitoring_and_adverse_event_monitoring' ->> 'df_value')::text AS vaccination_partners_mass_immunisation,
    (doc -> 'DForms' -> 'mvd_preparedness_surveillance' -> 0 -> 'DFields' -> 'values' -> 'public_health_personnel_are_trained_on_idsr_in_at_least_eighty_percent_of_the_highrisk_subcounties' ->> 'df_value')::text AS srv_ph_personnel_idsr_80percent,
    (doc -> 'DForms' -> 'mvd_preparedness_surveillance' -> 0 -> 'DFields' -> 'values' -> 'at_least_eighty_percent_of_public_health_facilities_are_prompt_in_reporting_potential_epidemic_diseases_including_acute_watery_diarrhoea_cases_through_idsr' ->> 'df_value')::text AS srv_public_health_facilities_reporting,
    (doc -> 'DForms' -> 'mvd_preparedness_surveillance' -> 0 -> 'DFields' -> 'values' -> 'county_has_a_community_based_definition_of_mvd_cases_in_at_least_eighty_percent_of_hotspots ' ->> 'df_value')::text AS srv_community_based_definitions_80percent,
    (doc -> 'DForms' -> 'mvd_preparedness_surveillance' -> 0 -> 'DFields' -> 'values' -> 'community_volunteers_are_trained_on_mvd_surveillance_and_reporting_in_at_least_eighty_percent_of_the_hotspots' ->> 'df_value')::text AS srv_community_volunteers_training,
    (doc -> 'DForms' -> 'mvd_preparedness_surveillance' -> 0 -> 'DFields' -> 'values' -> 'private_health_facilities_are_involved_in_vhfmvd_surveillance_in_at_least_eighty_percent_of_hotspots ' ->> 'df_value')::text AS srv_private_health_facilities_vhf,
    (doc -> 'DForms' -> 'mvd_preparedness_surveillance' -> 0 -> 'DFields' -> 'values' -> 'county_has_conducted_a_mvd_risk_assessment_mapping_with _tools_such_as_vram_star' ->> 'df_value')::text AS srv_risk_assessment_mapping,
    (doc -> 'DForms' -> 'mvd_preparedness_surveillance' -> 0 -> 'DFields' -> 'values' -> 'county_has_a_list_of_hotspots_high_risk_ubcounties_updated_within_the_last_three_years' ->> 'df_value')::text AS srv_hotspots_list_updated,
    (doc -> 'DForms' -> 'mvd_preparedness_surveillance' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_adequate_reporting_tools_at_all_levels_community' ->> 'df_value')::text AS srv_adequate_reporting_tools,
    (doc -> 'DForms' -> 'mvd_preparedness_surveillance' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_alert_desks_at_district_and_national_level_for_prompt_reporting_of_signals' ->> 'df_value')::text AS srv_alert_desks,
    (doc -> 'DForms' -> 'mvd_preparedness_surveillance' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_capacity_to_analysise_vhf_mvd_data_in_terms_of_person_place_and_time_at_different_levels' ->> 'df_value')::text AS srv_capacity_person_place_time,
    (doc -> 'DForms' -> 'mvd_preparedness_surveillance' -> 0 -> 'DFields' -> 'values' -> 'have_the_health_workers_who_are_working_in_hospitals_been_trained_in_ebs' ->> 'df_value')::text AS srv_hw_trained_in_ebs,
    (doc -> 'DForms' -> 'mvd_preparedness_case_management' -> 0 -> 'DFields' -> 'values' -> 'all_high_risk_subcounties_have_guidelines_protocols_and_other_monitoring_tools_for_vhf_mvd_case_management' ->> 'df_value')::text AS cm_guidelines_protocols,
    (doc -> 'DForms' -> 'mvd_preparedness_case_management' -> 0 -> 'DFields' -> 'values' -> 'at_least_eighty_percent_of_high_risk_subcounties_have_staff_trained_and_available_for_managing_vhf_mvd_cases' ->> 'df_value')::text AS cm_staff_trained_80percent,
    (doc -> 'DForms' -> 'mvd_preparedness_case_management' -> 0 -> 'DFields' -> 'values' -> 'at_least_eighty_percent_of_high_risk_subcounties_have_a_referral_system_in_place_from_the_community_to_the_health_facility' ->> 'df_value')::text AS cm_referral_system_80percent,
    (doc -> 'DForms' -> 'mvd_preparedness_general_information' -> 0 -> 'DFields' -> 'values' -> 'total_population' ->> 'df_value')::text AS geninfo_total_population,
    (doc -> 'DForms' -> 'mvd_preparedness_general_information' -> 0 -> 'DFields' -> 'values' -> 'number_of_subcounties' ->> 'df_value')::text AS geninfo_number_of_subcounties,
    (doc -> 'DForms' -> 'mvd_preparedness_general_information' -> 0 -> 'DFields' -> 'values' -> 'number_of_high_risk_subcounties' ->> 'df_value')::text AS geninfo_high_risk_subcounties,
    (doc -> 'DForms' -> 'mvd_preparedness_general_information' -> 0 -> 'DFields' -> 'values' -> 'number_of_health_facilities' ->> 'df_value')::text AS geninfo_health_facilities,
    (doc -> 'DForms' -> 'mvd_preparedness_general_information' -> 0 -> 'DFields' -> 'values' -> 'number_of_health_facilities_in_high_risk_subcounties' ->> 'df_value')::text AS geninfo_hf_in_high_risk_sc,
    (doc -> 'DForms' -> 'mvd_preparedness_general_information' -> 0 -> 'DFields' -> 'values' -> 'number_of_health_care_workers_in_high_risk_counties' ->> 'df_value')::text AS geninfo_hcw_in_high_risk_counties,
    (doc -> 'DForms' -> 'mvd_preparedness_general_information' -> 0 -> 'DFields' -> 'values' -> 'number_of_health_workers_trained_in_idsr' ->> 'df_value')::text AS geninfo_hw_trained_idsr,
    (doc -> 'DForms' -> 'mvd_preparedness_general_information' -> 0 -> 'DFields' -> 'values' -> 'number_of_health_facilities_reporting_mvd_cases_through_idsr' ->> 'df_value')::text AS geninfo_hf_reporting_mvd_idsr,
    (doc -> 'DForms' -> 'mvd_preparedness_general_information' -> 0 -> 'DFields' -> 'values' -> 'number_of_health_facilities_with_case_definitions_for_mvd' ->> 'df_value')::text AS geninfo_hf_with_case_defs_mvd,
    (doc -> 'DForms' -> 'mvd_preparedness_general_information' -> 0 -> 'DFields' -> 'values' -> 'number_of_health_facilities_with_mvd_case_investigation_and_linelisting_forms' ->> 'df_value')::text AS geninfo_hf_mvd_investigation_linelisting,
    (doc -> 'DForms' -> 'mvd_preparedness_general_information' -> 0 -> 'DFields' -> 'values' -> 'number_of_health_facilities_with_community_based_surveillance_structures_in_place' ->> 'df_value')::text AS geninfo_hf_with_cbs_structures,
    (doc -> 'DForms' -> 'mvd_preparedness_general_information' -> 0 -> 'DFields' -> 'values' -> 'number_of_community_health_volunteers_in_high_risk_communities' ->> 'df_value')::text AS geninfo_chv_in_high_risk_communities,
    (doc -> 'DForms' -> 'mvd_preparedness_general_information' -> 0 -> 'DFields' -> 'values' -> 'number_of_community_health_volunteers_trained_in_communitybased_surveillance_and_reporting' ->> 'df_value')::text AS geninfo_chv_trained_cbs_reporting,
    (doc -> 'DForms' -> 'mvd_preparedness_general_information' -> 0 -> 'DFields' -> 'values' -> 'number_of_health_facilities_in_high_risk_subcounties_with_viral _transport_media_and_rdt' ->> 'df_value')::text AS geninfo_hf_in_high_risk_sc_with_vtm_rdt,
    (doc -> 'DForms' -> 'mvd_preparedness_logistics_and_procurement' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_or_has_identified_temporary_or_permanent_case_management_facilities_in_at_least_80percent_of_high_risk_subcounties ' ->> 'df_value')::text AS logproc_case_mgmt_facilities_80percent,
    (doc -> 'DForms' -> 'mvd_preparedness_logistics_and_procurement' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_human_resources_capable_of_setting_up_isolation_units' ->> 'df_value')::text AS logproc_hr_isolation_units,
    (doc -> 'DForms' -> 'mvd_preparedness_logistics_and_procurement' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_pre_positioned_essential_stocks_at_national_and_regional_levels__and_in_at_least_80percent_of_high-risk_subcountiesfor_the_response_and_control_of_the_mvd_epidemic' ->> 'df_value')::text AS logproc_essential_stocks_80percent,
    (doc -> 'DForms' -> 'mvd_preparedness_logistics_and_procurement' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_a_functional_stock_monitoring_system_in_place_at_the_national_level_and_in_at_least_80percent_of_high_risk_subcounties ' ->> 'df_value')::text AS logproc_stock_monitoring_system_80percent,
    (doc -> 'DForms' -> 'mvd_preparedness_logistics_and_procurement' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_a_suppliers_list_of_key_items_and_other_services_for_emergency_response_at_the_local_level' ->> 'df_value')::text AS logproc_suppliers_list,
    (doc -> 'DForms' -> 'mvd_preparedness_human_resources_for_health' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_trained_surge_staff_roll_in_place ' ->> 'df_value')::text AS hrh_surge_staff_in_place,
    (doc -> 'DForms' -> 'mvd_preparedness_human_resources_for_health' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_adequate_clinical_staff_coverage' ->> 'df_value')::text AS hrh_clinical_staff_coverage,
    (doc -> 'DForms' -> 'mvd_preparedness_human_resources_for_health' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_protocols_in_place_for_task_shifting__rotation_of_staff_and_activating_surge_rosters' ->> 'df_value')::text AS hrh_task_shifting_protocols,
    (doc -> 'DForms' -> 'mvd_preparedness_coordination_and_leadership' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_established_multisectoral_mvd_focal_points' ->> 'df_value')::text AS coord_multisectoral_focal_points,
    (doc -> 'DForms' -> 'mvd_preparedness_coordination_and_leadership' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_a_multisectoral_coordination_mechanism_with_clear_terms_of_reference' ->> 'df_value')::text AS coord_multisectoral_mechanism,
    (doc -> 'DForms' -> 'mvd_preparedness_coordination_and_leadership' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_identified_key_performance_indicators_and_monitoring_of_mvd_response_including_quality_control_mechanisms' ->> 'df_value')::text AS coord_kpis_monitoring_quality_control,
    (doc -> 'DForms' -> 'mvd_preparedness_coordination_and_leadership' -> 0 -> 'DFields' -> 'values' -> 'county_has_a_resource_mobilisation_plan_for_vhf_infections' ->> 'df_value')::text AS coord_resource_mobilisation_plan,
    (doc -> 'DForms' -> 'mvd_preparedness_coordination_and_leadership' -> 0 -> 'DFields' -> 'values' -> 'risk_sub_counties_have_a_multi-sectoral_emergency_coordination_mechanism' ->> 'df_value')::text AS coord_risk_subcounties_multi_sectoral,
    (doc -> 'DForms' -> 'mvd_preparedness_coordination_and_leadership' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_an_updated_5w_of_partners' ->> 'df_value')::text AS coord_updated_5w_of_partners,
    (doc -> 'DForms' -> 'mvd_preparedness_coordination_and_leadership' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_conducted_at_least_one_simulation_exercise_to_test_its_capacity_to_respond_to_epidemics_including_vhf_within_the_last_6_months_or_one_year' ->> 'df_value')::text AS coord_simulation_exercise,
    (doc -> 'DForms' -> 'mvd_preparedness_risk_communication_and_community_engagement' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_designated_and_trained_spokespersons_on_epidemic_communication' ->> 'df_value')::text AS rcce_spokespersons_trained,
    (doc -> 'DForms' -> 'mvd_preparedness_risk_communication_and_community_engagement' -> 0 -> 'DFields' -> 'values' -> 'at_least_80percent_of_high_risk_subcounties_have_partnerships_with_local_media_companies_for_disseminating_key_messages_on_vhf_mvd' ->> 'df_value')::text AS rcce_media_partnerships,
    (doc -> 'DForms' -> 'mvd_preparedness_risk_communication_and_community_engagement' -> 0 -> 'DFields' -> 'values' -> 'at_least_eighty_percent_of_high_risk_subcounties_have_social_mobilisation_mechanisms_based_on_the_results_of_surveys_or_studies ' ->> 'df_value')::text AS rcce_social_mobilisation_mechanisms,
    (doc -> 'DForms' -> 'mvd_preparedness_risk_communication_and_community_engagement' -> 0 -> 'DFields' -> 'values' -> 'at_least_eighty_percent_of_high_risk_subcounties_have_trained_community_volunteers_on_key_messages_for_vhf_mvd_prevention_and_control' ->> 'df_value')::text AS rcce_trained_community_volunteers,
    (doc -> 'DForms' -> 'mvd_preparedness_risk_communication_and_community_engagement' -> 0 -> 'DFields' -> 'values' -> 'at_least_eighty_percent_of_high_risk_subcounties_have_key_messages_on_vhf_mvd_in_local_languages' ->> 'df_value')::text AS rcce_key_messages_local_languages,
    (doc -> 'DForms' -> 'mvd_preparedness_risk_communication_and_community_engagement' -> 0 -> 'DFields' -> 'values' -> 'at_least_eighty_percent_of_high_risk_subcounties_have_established_a_platform_to_engage_community_leaders_regularly_ for_enhanced_community_ownership_and_participation_in_mvd_prevention_and_control_activities' ->> 'df_value')::text AS rcce_platform_engage_community_leaders,
    (doc -> 'DForms' -> 'mvd_preparedness_risk_communication_and_community_engagement' -> 0 -> 'DFields' -> 'values' -> 'at_least_eighty_percent_of_high_risk_subcounties_have_exisiting_community_health_workers_intergrated_into_the_health_system_for_timely_response_and_sustainable_community_engagement_on_mvd' ->> 'df_value')::text AS rcce_existing_chws_in_high_risk,
    (doc -> 'DForms' -> 'mvd_preparedness_risk_communication_and_community_engagement' -> 0 -> 'DFields' -> 'values' -> 'the_county_has_established_communication_platforms_on_social_networks' ->> 'df_value')::text AS rcce_communication_platforms_social,
    (doc -> 'DForms' -> 'mvd_preparedness_risk_communication_and_community_engagement' -> 0 -> 'DFields' -> 'values' -> 'the_county_conducts_pre_and_post_outbreak_assessment_of_the_knowledge__attitutes_and_practices_of_community_members_evidence_based_ interventions' ->> 'df_value')::text AS rcce_pre_post_outbreak_assessment,
    (doc -> 'DForms' -> 'mvd_preparedness_risk_communication_and_community_engagement' -> 0 -> 'DFields' -> 'values' -> 'do_you_have_a_national_rcce_plan_in_place' ->> 'df_value')::text AS rcce_national_plan_in_place
FROM {{ source('couchdb', 'couchdb') }}
WHERE
    (doc ->> 'type')::text = 'dform'
AND
    (doc ->> 'mform_id')::text = '16eddd50-968c-11ef-9fa9-ff2039b96ab1'
