{{ config(
    materialized = 'table',
    indexes=[
      {'columns': ['syndrome']},
      {'columns': ['disease']},
      {'columns': ['id']},
      {'columns': ['parent_id']},
      {'columns': ['event_id']},
      {'columns': ['case_date']},
      {'columns': ['epi_week']},
      {'columns': ['type_of_case']},
      {'columns': ['country']},
      {'columns': ['county']},
      {'columns': ['subcounty']},
      {'columns': ['suspected']},
      {'columns': ['tested']},
      {'columns': ['confirmed']},
      {'columns': ['admitted']},
      {'columns': ['discharged']},
      {'columns': ['died']},
      {'columns': ['probable']},
      {'columns': ['contact']},
      {'columns': ['completed']},
    ]
)}}

SELECT 
    id,
    parent_id,
    contact_tree_label,
    mform_id,
    mform_event,
    event_id,
    form_id,
    case_unique_id,
    completed,
    parent_completed,
    created_role,
    modified_role,
    created_username,
    created_timestamp,
    modified_username,
    modified_timestamp,
    location_accuracy,
    location_latitude,
    location_longitude,
    syndrome,
    'Neonatal Tetanus'::text AS disease,
    case_date,
    epi_week,
    epid,
    date_of_investigation,
    location_of_investigation,
    location_of_investigation_other,
    CASE WHEN type_of_case IS NOT NULL THEN type_of_case ELSE 'Unknown' END AS type_of_case,
    given_name,
    family_name,
    sex,
    age_years,
    age_months,
    age_days,
    age_group,
    date_of_birth,
    case_is_pregnant,
    marital_status,
    phone_number,
    occupation,
    occupation_other,
    level_of_education,
    case_has_insurance_cover,
    country,
    county,
    subcounty,
    ward,
    town_village_camp,
    landmark,
    title_residence,
    type_of_residence,
    title_parent_guardian,
    guardian_family_name,
    guardian_given_name,
    guardian_phone_number,
    title_respondent,
    respondent,
    respondent_family_name,
    respondent_given_name,
    respondent_address,
    respondent_phone_number,
    respondent_relationship,
    delivery_location,
    sterile_code_cutter,
    cord_stump_treated,
    baby_age_days,
    baby_suckling_normally,
    confirmed_nnt,
    baby_treated_at_facility,
    baby_mother_alive,
    title_clinical_care,
    type_of_care,
    date_of_admission,
    inpatient_number,
    name_of_health_facility,
    mfl_number_of_health_facility,
    outcome_of_patient,
    status_of_patient,
    date_of_discharge,
    date_of_death,
    laboratory_samples_were_collected,
    laboratory_samples_collected,
    laboratory_samples_collected_other,
    date_of_sample_collection,
    result_of_laboratory_test,
    date_of_laboratory_results,
    title_laboratory_facility,
    name_of_laboratory_facility,
    mfl_number_of_laboratory_facility,
    (1)::integer AS suspected,
    (CASE WHEN laboratory_samples_were_collected = 'Yes' THEN 1 ELSE 0 END)::integer AS tested,
    (CASE WHEN confirmed_nnt = 'Yes' THEN 1 WHEN type_of_case = 'Confirmed' THEN 1 WHEN result_of_laboratory_test = 'Positive' THEN 1 ELSE 0 END)::integer AS confirmed,
    (CASE WHEN status_of_patient = 'Admitted' THEN 1 ELSE 0 END)::integer AS admitted,
    (CASE WHEN status_of_patient = 'Discharged' THEN 1 ELSE 0 END)::integer AS discharged,
    (CASE WHEN outcome_of_patient = 'Dead' THEN 1 ELSE 0 END)::integer AS died,
    (CASE WHEN type_of_case = 'Probable' THEN 1 ELSE 0 END)::integer AS probable,
    (CASE WHEN type_of_case = 'Contact' THEN 1 ELSE 0 END)::integer AS contact,
    current_date AS load_date
FROM {{ ref('int_neonatal_tetanus') }}
