{{ config(
    materialized = 'table',
    indexes=[
      {'columns': ['id']},
      {'columns': ['parent_id']},
      {'columns': ['event_id']},
      {'columns': ['completed']},
      {'columns': ['case_date']},
      {'columns': ['epi_week']},
      {'columns': ['type_of_case']},
      {'columns': ['country']},
      {'columns': ['county']},
      {'columns': ['subcounty']},
    ]
)}}

SELECT 
    id,
    parent_id,
    contact_tree_label,
    mform_id,
    mform_event,
    event_id,
    form_id,
    case_unique_id,
    completed,
    parent_completed,
    created_role,
    modified_role,
    created_username,
    created_timestamp,
    modified_username,
    modified_timestamp,
    location_accuracy,
    location_latitude,
    location_longitude,
    syndrome,
    disease,
    case_date,
    epi_week,
    epid,
    date_of_investigation,
    location_of_investigation,
    location_of_investigation_other,
    type_of_case,
    given_name,
    family_name,
    sex,
    age_years,
    age_months,
    age_days,
    age_group,
    date_of_birth,
    case_is_pregnant,
    phone_number,
    marital_status,
    occupation,
    occupation_other,
    level_of_education,
    case_has_insurance_cover,
    country,
    county,
    subcounty,
    ward,
    town_village_camp,
    landmark,
    title_residence,
    type_of_residence,
    title_parent_guardian,
    guardian_family_name,
    guardian_given_name,
    guardian_phone_number,
    title_respondent,
    respondent,
    respondent_family_name,
    respondent_given_name,
    respondent_address,
    respondent_phone_number,
    respondent_relationship,
    exposure_type_rabies,
    exposure_date,
    exposure_rabies_injury,
    exposure_rabies_injury_site,
    animal_species,
    animal_species_other,
    animal_vaccinated,
    animal_rabies_suspect,
    animal_observed,
    animal_dead,
    animal_dead_days,
    repondent,
    repondent_family_name,
    repondent_given_name,
    repondent_phone_number,
    repondent_address,
    repondent_relationship,
    repondent_relationship_other,
    vaccinated,
    vaccine_name,
    vaccine_doses,
    health_facility,
    vaccination_date,
    case_seen_at_facility,
    date_first_seen_at_facility,
    admitted,
    health_facility_name,
    admission_date,
    inpatient_number,
    discharge_date,
    patient_status
FROM {{ ref('int_rabies') }}
