{{ config(
    materialized = 'table',
    indexes=[
      {'columns': ['syndrome']},
      {'columns': ['disease']},
      {'columns': ['id']},
      {'columns': ['parent_id']},
      {'columns': ['event_id']},
      {'columns': ['case_date']},
      {'columns': ['epi_week']},
      {'columns': ['type_of_case']},
      {'columns': ['country']},
      {'columns': ['county']},
      {'columns': ['subcounty']},
      {'columns': ['total']},
      {'columns': ['suspected']},
      {'columns': ['tested']},
      {'columns': ['confirmed']},
      {'columns': ['admitted']},
      {'columns': ['discharged']},
      {'columns': ['died']},
      {'columns': ['probable']},
      {'columns': ['contact']},
      {'columns': ['completed']},
      {'columns': ['hierarchy_level']},
      {'columns': ['has_children']}
    ]
)}}

WITH RECURSIVE

root_node AS (
    SELECT
        'a52f1b40-89b1-22df-a632-9dcf84b7c058'::text AS id,
        ''::text AS parent_id,
        0 AS hierarchy_level,
        'ROOT'::text AS contact_tree_label,
        NULL AS mform_id,
        NULL AS mform_event,
        NULL AS event_id,
        NULL AS form_id,
        NULL AS case_unique_id,
        'Draft'::text AS completed,
        NULL AS parent_completed,
        NULL AS created_role,
        NULL AS modified_role,
        NULL AS created_username,
        NULL AS created_timestamp,
        NULL AS modified_username,
        NULL AS modified_timestamp,
        NULL AS location_accuracy,
        NULL AS location_latitude,
        NULL AS location_longitude,
        NULL AS syndrome,
        'Rabies'::text AS disease,
        null::date AS case_date,
        NULL AS epi_week,
        NULL AS epid,
        NULL AS date_of_investigation,
        NULL AS location_of_investigation,
        NULL AS location_of_investigation_other,
        NULL AS type_of_case,
        NULL AS given_name,
        NULL AS family_name,
        NULL AS sex,
        null::double precision AS age_years,
        null::double precision AS age_months,
        null::double precision AS age_days,
        NULL AS age_group,
        NULL::date AS date_of_birth,
        NULL AS case_is_pregnant,
        NULL AS phone_number,
        NULL AS marital_status,
        NULL AS occupation,
        NULL AS occupation_other,
        NULL AS level_of_education,
        NULL AS case_has_insurance_cover,
        NULL AS country,
        NULL AS county,
        NULL AS subcounty,
        NULL AS ward,
        NULL AS town_village_camp,
        NULL AS landmark,
        NULL AS title_residence,
        NULL AS type_of_residence,
        NULL AS title_parent_guardian,
        NULL AS guardian_family_name,
        NULL AS guardian_given_name,
        NULL AS guardian_phone_number,
        NULL AS title_respondent,
        NULL AS respondent,
        NULL AS respondent_family_name,
        NULL AS respondent_given_name,
        NULL AS respondent_address,
        NULL AS respondent_phone_number,
        NULL AS respondent_relationship,
        NULL AS exposure_type_rabies,
        NULL AS exposure_date,
        NULL AS exposure_rabies_injury,
        NULL AS exposure_rabies_injury_site,
        NULL AS animal_species,
        NULL AS animal_species_other,
        NULL AS animal_vaccinated,
        NULL AS animal_rabies_suspect,
        NULL AS animal_observed,
        NULL AS animal_dead,
        NULL AS animal_dead_days,
        NULL AS repondent,
        NULL AS repondent_family_name,
        NULL AS repondent_given_name,
        NULL AS repondent_phone_number,
        NULL AS repondent_address,
        NULL AS repondent_relationship,
        NULL AS repondent_relationship_other,
        NULL AS vaccinated,
        NULL AS vaccine_name,
        NULL AS vaccine_doses,
        NULL AS health_facility,
        NULL AS vaccination_date,
        NULL AS case_seen_at_facility,
        NULL AS date_first_seen_at_facility,
        NULL AS case_admitted,
        NULL AS health_facility_name,
        NULL AS admission_date,
        NULL AS inpatient_number,
        NULL AS discharge_date,
        NULL AS patient_status,
        0::integer AS total,
        0::integer AS suspected,
        0::integer AS tested,
        0::integer AS confirmed,
        0::integer AS admitted,
        0::integer AS discharged,
        0::integer AS died,
        0::integer AS probable,
        0::integer AS contact,
        current_date AS load_date
),

hierarchy AS (
    SELECT * FROM root_node
    
    UNION ALL

    SELECT 
        c.id,
        CASE 
            WHEN c.parent_id IS NULL OR c.parent_id = '' THEN 'a52f1b40-89b1-22df-a632-9dcf84b7c058'
            ELSE c.parent_id
        END AS parent_id,
        h.hierarchy_level + 1 AS hierarchy_level,
        c.contact_tree_label,
        c.mform_id,
        c.mform_event,
        c.event_id,
        c.form_id,
        c.case_unique_id,
        c.completed,
        c.parent_completed,
        c.created_role,
        c.modified_role,
        c.created_username,
        c.created_timestamp,
        c.modified_username,
        c.modified_timestamp,
        c.location_accuracy,
        c.location_latitude,
        c.location_longitude,
        c.syndrome,
        'Rabies'::text AS disease,
        c.case_date,
        c.epi_week,
        c.epid,
        c.date_of_investigation,
        c.location_of_investigation,
        c.location_of_investigation_other,
        c.type_of_case,
        c.given_name,
        c.family_name,
        c.sex,
        c.age_years,
        c.age_months,
        c.age_days,
        c.age_group,
        c.date_of_birth,
        c.case_is_pregnant,
        c.phone_number,
        c.marital_status,
        c.occupation,
        c.occupation_other,
        c.level_of_education,
        c.case_has_insurance_cover,
        c.country,
        c.county,
        c.subcounty,
        c.ward,
        c.town_village_camp,
        c.landmark,
        c.title_residence,
        c.type_of_residence,
        c.title_parent_guardian,
        c.guardian_family_name,
        c.guardian_given_name,
        c.guardian_phone_number,
        c.title_respondent,
        c.respondent,
        c.respondent_family_name,
        c.respondent_given_name,
        c.respondent_address,
        c.respondent_phone_number,
        c.respondent_relationship,
        c.exposure_type_rabies,
        c.exposure_date,
        c.exposure_rabies_injury,
        c.exposure_rabies_injury_site,
        c.animal_species,
        c.animal_species_other,
        c.animal_vaccinated,
        c.animal_rabies_suspect,
        c.animal_observed,
        c.animal_dead,
        c.animal_dead_days,
        c.repondent,
        c.repondent_family_name,
        c.repondent_given_name,
        c.repondent_phone_number,
        c.repondent_address,
        c.repondent_relationship,
        c.repondent_relationship_other,
        c.vaccinated,
        c.vaccine_name,
        c.vaccine_doses,
        c.health_facility,
        c.vaccination_date,
        c.case_seen_at_facility,
        c.date_first_seen_at_facility,
        c.admitted AS case_admitted,
        c.health_facility_name,
        c.admission_date,
        c.inpatient_number,
        c.discharge_date,
        c.patient_status,
        (1)::integer AS total,
        (1)::integer AS suspected,
        (CASE WHEN c.exposure_type_rabies IS NOT NULL THEN 1 ELSE 0 END)::integer AS tested,
        (CASE WHEN c.type_of_case = 'Confirmed' THEN 1 ELSE 0 END)::integer AS confirmed,
        (CASE WHEN c.admitted = 'Yes' THEN 1 ELSE 0 END)::integer AS admitted,
        (CASE WHEN c.patient_status = 'Discharged' THEN 1 ELSE 0 END)::integer AS discharged,
        (CASE WHEN c.patient_status = 'Dead' THEN 1 ELSE 0 END)::integer AS died,
        (CASE WHEN c.type_of_case = 'Probable' THEN 1 ELSE 0 END)::integer AS probable,
        (CASE WHEN c.type_of_case = 'Contact' THEN 1 ELSE 0 END)::integer AS contact,
        current_date AS load_date
    FROM {{ ref('int_rabies') }} c
    INNER JOIN hierarchy h ON 
        CASE 
            WHEN c.parent_id IS NULL OR c.parent_id = '' THEN 'a52f1b40-89b1-22df-a632-9dcf84b7c058'
            ELSE c.parent_id
        END = h.id
    WHERE NOT (c.id = 'a52f1b40-89b1-22df-a632-9dcf84b7c058')
),

first_level_orphans AS (
    SELECT 
        c.id,
        'a52f1b40-89b1-22df-a632-9dcf84b7c058' AS parent_id,
        1 AS hierarchy_level,
        c.contact_tree_label,
        c.mform_id,
        c.mform_event,
        c.event_id,
        c.form_id,
        c.case_unique_id,
        c.completed,
        c.parent_completed,
        c.created_role,
        c.modified_role,
        c.created_username,
        c.created_timestamp,
        c.modified_username,
        c.modified_timestamp,
        c.location_accuracy,
        c.location_latitude,
        c.location_longitude,
        c.syndrome,
        'Rabies'::text AS disease,
        c.case_date,
        c.epi_week,
        c.epid,
        c.date_of_investigation,
        c.location_of_investigation,
        c.location_of_investigation_other,
        c.type_of_case,
        c.given_name,
        c.family_name,
        c.sex,
        c.age_years,
        c.age_months,
        c.age_days,
        c.age_group,
        c.date_of_birth,
        c.case_is_pregnant,
        c.phone_number,
        c.marital_status,
        c.occupation,
        c.occupation_other,
        c.level_of_education,
        c.case_has_insurance_cover,
        c.country,
        c.county,
        c.subcounty,
        c.ward,
        c.town_village_camp,
        c.landmark,
        c.title_residence,
        c.type_of_residence,
        c.title_parent_guardian,
        c.guardian_family_name,
        c.guardian_given_name,
        c.guardian_phone_number,
        c.title_respondent,
        c.respondent,
        c.respondent_family_name,
        c.respondent_given_name,
        c.respondent_address,
        c.respondent_phone_number,
        c.respondent_relationship,
        c.exposure_type_rabies,
        c.exposure_date,
        c.exposure_rabies_injury,
        c.exposure_rabies_injury_site,
        c.animal_species,
        c.animal_species_other,
        c.animal_vaccinated,
        c.animal_rabies_suspect,
        c.animal_observed,
        c.animal_dead,
        c.animal_dead_days,
        c.repondent,
        c.repondent_family_name,
        c.repondent_given_name,
        c.repondent_phone_number,
        c.repondent_address,
        c.repondent_relationship,
        c.repondent_relationship_other,
        c.vaccinated,
        c.vaccine_name,
        c.vaccine_doses,
        c.health_facility,
        c.vaccination_date,
        c.case_seen_at_facility,
        c.date_first_seen_at_facility,
        c.admitted as case_admitted,
        c.health_facility_name,
        c.admission_date,
        c.inpatient_number,
        c.discharge_date,
        c.patient_status,
        (1)::integer AS total,
        (1)::integer AS suspected,
        (CASE WHEN c.exposure_type_rabies IS NOT NULL THEN 1 ELSE 0 END)::integer AS tested,
        (CASE WHEN c.type_of_case = 'Confirmed' THEN 1 ELSE 0 END)::integer AS confirmed,
        (CASE WHEN c.admitted = 'Yes' THEN 1 ELSE 0 END)::integer AS admitted,
        (CASE WHEN c.patient_status = 'Discharged' THEN 1 ELSE 0 END)::integer AS discharged,
        (CASE WHEN c.patient_status = 'Dead' THEN 1 ELSE 0 END)::integer AS died,
        (CASE WHEN c.type_of_case = 'Probable' THEN 1 ELSE 0 END)::integer AS probable,
        (CASE WHEN c.type_of_case = 'Contact' THEN 1 ELSE 0 END)::integer AS contact,
        current_date AS load_date
    FROM {{ ref('int_rabies') }} c
    LEFT JOIN hierarchy h ON c.parent_id = h.id
    WHERE h.id IS NULL 
      AND c.parent_id IS NOT NULL 
      AND c.parent_id != '' 
      AND c.id != 'a52f1b40-89b1-22df-a632-9dcf84b7c058'
),

combined_hierarchy AS (
    SELECT * FROM hierarchy
    UNION ALL
    SELECT * FROM first_level_orphans
)

SELECT
    h.id,
    h.parent_id,
    h.hierarchy_level,
    CASE 
        WHEN EXISTS (
            SELECT 1 
            FROM {{ ref('int_rabies') }} child 
            WHERE child.parent_id = h.id
        ) THEN true
        ELSE false
    END as has_children,
    h.contact_tree_label,
    h.mform_id,
    h.mform_event,
    h.event_id,
    h.form_id,
    h.case_unique_id,
    h.completed,
    h.parent_completed,
    h.created_role,
    h.modified_role,
    h.created_username,
    h.created_timestamp,
    h.modified_username,
    h.modified_timestamp,
    h.location_accuracy,
    h.location_latitude,
    h.location_longitude,
    h.syndrome,
    'Rabies'::text AS disease,
    h.case_date,
    h.epi_week,
    h.epid,
    h.date_of_investigation,
    h.location_of_investigation,
    h.location_of_investigation_other,
    CASE WHEN h.type_of_case IS NOT NULL THEN h.type_of_case ELSE 'Unknown' END AS type_of_case,
    h.given_name,
    h.family_name,
    h.sex,
    h.age_years,
    h.age_months,
    h.age_days,
    h.age_group,
    h.date_of_birth,
    h.case_is_pregnant,
    h.phone_number,
    h.marital_status,
    h.occupation,
    h.occupation_other,
    h.level_of_education,
    h.case_has_insurance_cover,
    h.country,
    h.county,
    h.subcounty,
    h.ward,
    h.town_village_camp,
    h.landmark,
    h.title_residence,
    h.type_of_residence,
    h.title_parent_guardian,
    h.guardian_family_name,
    h.guardian_given_name,
    h.guardian_phone_number,
    h.title_respondent,
    h.respondent,
    h.respondent_family_name,
    h.respondent_given_name,
    h.respondent_address,
    h.respondent_phone_number,
    h.respondent_relationship,
    h.exposure_type_rabies,
    h.exposure_date,
    h.exposure_rabies_injury,
    h.exposure_rabies_injury_site,
    h.animal_species,
    h.animal_species_other,
    h.animal_vaccinated,
    h.animal_rabies_suspect,
    h.animal_observed,
    h.animal_dead,
    h.animal_dead_days,
    h.repondent,
    h.repondent_family_name,
    h.repondent_given_name,
    h.repondent_phone_number,
    h.repondent_address,
    h.repondent_relationship,
    h.repondent_relationship_other,
    h.vaccinated,
    h.vaccine_name,
    h.vaccine_doses,
    h.health_facility,
    h.vaccination_date,
    h.case_seen_at_facility,
    h.date_first_seen_at_facility,
    h.case_admitted,
    h.health_facility_name,
    h.admission_date,
    h.inpatient_number,
    h.discharge_date,
    h.patient_status,
    h.total,
    h.suspected,
    h.tested,
    h.confirmed,
    h.admitted,
    h.discharged,
    h.died,
    h.probable,
    h.contact,
    h.load_date
FROM combined_hierarchy h
