{{ config(
    materialized = 'table',
    indexes=[
      {'columns': ['syndrome']},
      {'columns': ['disease']},
      {'columns': ['id']},
      {'columns': ['parent_id']},
      {'columns': ['event_id']},
      {'columns': ['case_date']},
      {'columns': ['epi_week']},
      {'columns': ['type_of_case']},
      {'columns': ['country']},
      {'columns': ['county']},
      {'columns': ['subcounty']},
      {'columns': ['total']},
      {'columns': ['suspected']},
      {'columns': ['tested']},
      {'columns': ['confirmed']},
      {'columns': ['admitted']},
      {'columns': ['discharged']},
      {'columns': ['died']},
      {'columns': ['probable']},
      {'columns': ['contact']},
      {'columns': ['completed']},
      {'columns': ['hierarchy_level']},
      {'columns': ['has_children']}
    ]
)}}

WITH RECURSIVE

root_node AS (
    SELECT
        'a52f1b40-89b1-22df-a632-9dcf84b7c056'::text AS id,
        ''::text AS parent_id,
        0 AS hierarchy_level,
        'ROOT'::text AS contact_tree_label,
        NULL AS mform_id,
        NULL AS mform_event,
        NULL AS event_id,
        NULL AS form_id,
        NULL AS case_unique_id,
        'Draft'::text AS completed,
        NULL AS parent_completed,
        NULL AS created_role,
        NULL AS modified_role,
        NULL AS created_username,
        NULL AS created_timestamp,
        NULL AS modified_username,
        NULL AS modified_timestamp,
        NULL AS location_accuracy,
        NULL AS location_latitude,
        NULL AS location_longitude,
        NULL AS syndrome,
        'Meningitis'::text AS disease,
        null::date AS case_date,
        NULL AS epi_week,
        NULL AS epid,
        NULL AS date_of_investigation,
        NULL AS location_of_investigation,
        NULL AS location_of_investigation_other,
        NULL AS type_of_case,
        NULL AS given_name,
        NULL AS family_name,
        NULL AS sex,
        null::double precision AS age_years,
        null::double precision AS age_months,
        null::double precision AS age_days,
        NULL AS age_group,
        NULL AS date_of_birth,
        NULL AS phone_number,
        NULL AS occupation,
        NULL AS occupation_other,
        NULL AS marital_status,
        NULL AS case_is_pregnant,
        NULL AS case_has_insurance_cover,
        NULL AS level_of_education,
        NULL AS type_of_residence,
        NULL AS ward,
        NULL AS country,
        NULL AS county,
        NULL AS subcounty,
        NULL AS town_village_camp,
        NULL AS landmark,
        NULL AS title_residence,
        NULL AS title_parent_guardian,
        NULL AS guardian_family_name,
        NULL AS guardian_given_name,
        NULL AS guardian_phone_number,
        NULL AS title_respondent,
        NULL AS respondent,
        NULL AS respondent_family_name,
        NULL AS respondent_given_name,
        NULL AS respondent_address,
        NULL AS respondent_phone_number,
        NULL AS respondent_relationship,
        NULL AS reporting_county,
        NULL AS reporting_subcounty,
        NULL AS reporting_health_facility,
        NULL AS vaccine,
        NULL AS vaccination_exists,
        NULL AS vaccine_meningitis,
        NULL AS vaccine_doses,
        NULL AS vaccine_last_dose_date,
        NULL AS vaccine_information_source,
        NULL AS lumbar_puncture_date,
        NULL AS lumbar_puncture_time,
        NULL AS celebrospinal_fluid_appearance,
        NULL AS inoculation_date,
        NULL AS inoculation_time,
        NULL AS sample_transport_medium,
        NULL AS sample_transport_medium_others,
        NULL AS laboratory_test_requested,
        NULL AS reference_laboratory,
        NULL AS laboratory_information_exists,
        NULL AS laboratory_samples_collected,
        NULL AS appearance_of_sttol_sample,
        NULL AS laboratory_tests,
        NULL AS laboratory_tests_other,
        NULL AS title_results,
        NULL AS leucocytes_results,
        NULL AS pn_results,
        NULL AS lymp_results,
        NULL AS gram_results,
        NULL AS rdt_results,
        NULL AS serology_results,
        NULL AS laboratory_results_other,
        NULL AS date_of_laboratory_results,
        NULL AS title_laboratory_facility,
        NULL AS name_of_laboratory,
        NULL AS patient_on_treatment,
        NULL AS patient_on_treatment_specify,
        NULL AS symptoms,
        NULL AS date_of_onset,
        NULL AS clinical_health_facility,
        NULL AS name_of_health_facility,
        NULL AS date_first_seen_at_facility,
        NULL AS admission_date,
        NULL AS patient_status,
        NULL AS status_of_case,
        NULL AS outcome_of_case,
        NULL AS date_of_discharge,
        NULL AS date_of_death,
        NULL AS place_of_death,
        NULL AS inpatient_number,
        NULL AS outpatient_number,
        NULL AS title_clinical_care,
        NULL AS type_of_care,
        0::integer AS total,
        0::integer AS suspected,
        0::integer AS tested,
        0::integer AS confirmed,
        0::integer AS admitted,
        0::integer AS discharged,
        0::integer AS died,
        0::integer AS probable,
        0::integer AS contact,
        current_date AS load_date
),

hierarchy AS (
    SELECT * FROM root_node
    
    UNION ALL

    SELECT 
        c.id,
        CASE 
            WHEN c.parent_id IS NULL OR c.parent_id = '' THEN 'a52f1b40-89b1-22df-a632-9dcf84b7c056'
            ELSE c.parent_id
        END AS parent_id,
        h.hierarchy_level + 1 AS hierarchy_level,
        c.contact_tree_label,
        c.mform_id,
        c.mform_event,
        c.event_id,
        c.form_id,
        c.case_unique_id,
        c.completed,
        c.parent_completed,
        c.created_role,
        c.modified_role,
        c.created_username,
        c.created_timestamp,
        c.modified_username,
        c.modified_timestamp,
        c.location_accuracy,
        c.location_latitude,
        c.location_longitude,
        c.syndrome,
        c.disease,
        c.case_date,
        c.epi_week,
        c.epid,
        c.date_of_investigation,
        c.location_of_investigation,
        c.location_of_investigation_other,
        c.type_of_case,
        c.given_name,
        c.family_name,
        c.sex,
        c.age_years,
        c.age_months,
        c.age_days,
        c.age_group,
        c.date_of_birth,
        c.phone_number,
        c.occupation,
        c.occupation_other,
        c.marital_status,
        c.case_is_pregnant,
        c.case_has_insurance_cover,
        c.level_of_education,
        c.type_of_residence,
        c.ward,
        c.country,
        c.county,
        c.subcounty,
        c.town_village_camp,
        c.landmark,
        c.title_residence,
        c.title_parent_guardian,
        c.guardian_family_name,
        c.guardian_given_name,
        c.guardian_phone_number,
        c.title_respondent,
        c.respondent,
        c.respondent_family_name,
        c.respondent_given_name,
        c.respondent_address,
        c.respondent_phone_number,
        c.respondent_relationship,
        c.reporting_county,
        c.reporting_subcounty,
        c.reporting_health_facility,
        c.vaccine,
        c.vaccination_exists,
        c.vaccine_meningitis,
        c.vaccine_doses,
        c.vaccine_last_dose_date,
        c.vaccine_information_source,
        c.lumbar_puncture_date,
        c.lumbar_puncture_time,
        c.celebrospinal_fluid_appearance,
        c.inoculation_date,
        c.inoculation_time,
        c.sample_transport_medium,
        c.sample_transport_medium_others,
        c.laboratory_test_requested,
        c.reference_laboratory,
        c.laboratory_information_exists,
        c.laboratory_samples_collected,
        c.appearance_of_sttol_sample,
        c.laboratory_tests,
        c.laboratory_tests_other,
        c.title_results,
        c.leucocytes_results,
        c.pn_results,
        c.lymp_results,
        c.gram_results,
        c.rdt_results,
        c.serology_results,
        c.laboratory_results_other,
        c.date_of_laboratory_results,
        c.title_laboratory_facility,
        c.name_of_laboratory,
        c.patient_on_treatment,
        c.patient_on_treatment_specify,
        c.symptoms,
        c.date_of_onset,
        c.clinical_health_facility,
        c.name_of_health_facility,
        c.date_first_seen_at_facility,
        c.admission_date,
        c.patient_status,
        c.status_of_case,
        c.outcome_of_case,
        c.date_of_discharge,
        c.date_of_death,
        c.place_of_death,
        c.inpatient_number,
        c.outpatient_number,
        c.title_clinical_care,
        c.type_of_care,
        (1)::integer AS total,
        (1)::integer AS suspected,
        (CASE WHEN c.laboratory_tests IS NOT NULL THEN 1 WHEN c.laboratory_tests_other IS NOT NULL THEN 1 ELSE 0 END)::integer AS tested,
        (CASE WHEN c.type_of_case = 'Confirmed' THEN 1 ELSE 0 END)::integer AS confirmed,
        (CASE WHEN c.patient_status = 'Admitted' THEN 1 ELSE 0 END)::integer AS admitted,
        (CASE WHEN c.patient_status = 'Discharged' THEN 1 ELSE 0 END)::integer AS discharged,
        (CASE WHEN c.patient_status = 'Dead' THEN 1 ELSE 0 END)::integer AS died,
        (CASE WHEN c.type_of_case = 'Probable' THEN 1 ELSE 0 END)::integer AS probable,
        (CASE WHEN c.type_of_case = 'Contact' THEN 1 ELSE 0 END)::integer AS contact,
        current_date AS load_date
    FROM {{ ref('int_meningitis') }} c
    INNER JOIN hierarchy h ON 
        CASE 
            WHEN c.parent_id IS NULL OR c.parent_id = '' THEN 'a52f1b40-89b1-22df-a632-9dcf84b7c056'
            ELSE c.parent_id
        END = h.id
    WHERE NOT (c.id = 'a52f1b40-89b1-22df-a632-9dcf84b7c056')
),

first_level_orphans AS (
    SELECT 
        c.id,
        'a52f1b40-89b1-22df-a632-9dcf84b7c056' AS parent_id,
        1 AS hierarchy_level,
        c.contact_tree_label,
        c.mform_id,
        c.mform_event,
        c.event_id,
        c.form_id,
        c.case_unique_id,
        c.completed,
        c.parent_completed,
        c.created_role,
        c.modified_role,
        c.created_username,
        c.created_timestamp,
        c.modified_username,
        c.modified_timestamp,
        c.location_accuracy,
        c.location_latitude,
        c.location_longitude,
        c.syndrome,
        c.disease,
        c.case_date,
        c.epi_week,
        c.epid,
        c.date_of_investigation,
        c.location_of_investigation,
        c.location_of_investigation_other,
        c.type_of_case,
        c.given_name,
        c.family_name,
        c.sex,
        c.age_years,
        c.age_months,
        c.age_days,
        c.age_group,
        c.date_of_birth,
        c.phone_number,
        c.occupation,
        c.occupation_other,
        c.marital_status,
        c.case_is_pregnant,
        c.case_has_insurance_cover,
        c.level_of_education,
        c.type_of_residence,
        c.ward,
        c.country,
        c.county,
        c.subcounty,
        c.town_village_camp,
        c.landmark,
        c.title_residence,
        c.title_parent_guardian,
        c.guardian_family_name,
        c.guardian_given_name,
        c.guardian_phone_number,
        c.title_respondent,
        c.respondent,
        c.respondent_family_name,
        c.respondent_given_name,
        c.respondent_address,
        c.respondent_phone_number,
        c.respondent_relationship,
        c.reporting_county,
        c.reporting_subcounty,
        c.reporting_health_facility,
        c.vaccine,
        c.vaccination_exists,
        c.vaccine_meningitis,
        c.vaccine_doses,
        c.vaccine_last_dose_date,
        c.vaccine_information_source,
        c.lumbar_puncture_date,
        c.lumbar_puncture_time,
        c.celebrospinal_fluid_appearance,
        c.inoculation_date,
        c.inoculation_time,
        c.sample_transport_medium,
        c.sample_transport_medium_others,
        c.laboratory_test_requested,
        c.reference_laboratory,
        c.laboratory_information_exists,
        c.laboratory_samples_collected,
        c.appearance_of_sttol_sample,
        c.laboratory_tests,
        c.laboratory_tests_other,
        c.title_results,
        c.leucocytes_results,
        c.pn_results,
        c.lymp_results,
        c.gram_results,
        c.rdt_results,
        c.serology_results,
        c.laboratory_results_other,
        c.date_of_laboratory_results,
        c.title_laboratory_facility,
        c.name_of_laboratory,
        c.patient_on_treatment,
        c.patient_on_treatment_specify,
        c.symptoms,
        c.date_of_onset,
        c.clinical_health_facility,
        c.name_of_health_facility,
        c.date_first_seen_at_facility,
        c.admission_date,
        c.patient_status,
        c.status_of_case,
        c.outcome_of_case,
        c.date_of_discharge,
        c.date_of_death,
        c.place_of_death,
        c.inpatient_number,
        c.outpatient_number,
        c.title_clinical_care,
        c.type_of_care,
        (1)::integer AS total,
        (1)::integer AS suspected,
        (CASE WHEN c.laboratory_tests IS NOT NULL THEN 1 WHEN c.laboratory_tests_other IS NOT NULL THEN 1 ELSE 0 END)::integer AS tested,
        (CASE WHEN c.type_of_case = 'Confirmed' THEN 1 ELSE 0 END)::integer AS confirmed,
        (CASE WHEN c.patient_status = 'Admitted' THEN 1 ELSE 0 END)::integer AS admitted,
        (CASE WHEN c.patient_status = 'Discharged' THEN 1 ELSE 0 END)::integer AS discharged,
        (CASE WHEN c.patient_status = 'Dead' THEN 1 ELSE 0 END)::integer AS died,
        (CASE WHEN c.type_of_case = 'Probable' THEN 1 ELSE 0 END)::integer AS probable,
        (CASE WHEN c.type_of_case = 'Contact' THEN 1 ELSE 0 END)::integer AS contact,
        current_date AS load_date
    FROM {{ ref('int_meningitis') }} c
    LEFT JOIN hierarchy h ON c.parent_id = h.id
    WHERE h.id IS NULL 
      AND c.parent_id IS NOT NULL 
      AND c.parent_id != '' 
      AND c.id != 'a52f1b40-89b1-22df-a632-9dcf84b7c056'
),

combined_hierarchy AS (
    SELECT * FROM hierarchy
    UNION ALL
    SELECT * FROM first_level_orphans
)

SELECT
    h.id,
    h.parent_id,
    h.hierarchy_level,
    CASE 
        WHEN EXISTS (
            SELECT 1 
            FROM {{ ref('int_meningitis') }} child 
            WHERE child.parent_id = h.id
        ) THEN true
        ELSE false
    END as has_children,
    h.contact_tree_label,
    h.mform_id,
    h.mform_event,
    h.event_id,
    h.form_id,
    h.case_unique_id,
    h.completed,
    h.parent_completed,
    h.created_role,
    h.modified_role,
    h.created_username,
    h.created_timestamp,
    h.modified_username,
    h.modified_timestamp,
    h.location_accuracy,
    h.location_latitude,
    h.location_longitude,
    h.syndrome,
    'Meningitis'::text AS disease,
    h.case_date,
    h.epi_week,
    h.epid,
    h.date_of_investigation,
    h.location_of_investigation,
    h.location_of_investigation_other,
    CASE WHEN h.type_of_case IS NOT NULL THEN h.type_of_case ELSE 'Unknown' END AS type_of_case,
    h.given_name,
    h.family_name,
    h.sex,
    h.age_years,
    h.age_months,
    h.age_days,
    h.age_group,
    h.date_of_birth,
    h.phone_number,
    h.occupation,
    h.occupation_other,
    h.marital_status,
    h.case_is_pregnant,
    h.case_has_insurance_cover,
    h.level_of_education,
    h.type_of_residence,
    h.ward,
    h.country,
    h.county,
    h.subcounty,
    h.town_village_camp,
    h.landmark,
    h.title_residence,
    h.title_parent_guardian,
    h.guardian_family_name,
    h.guardian_given_name,
    h.guardian_phone_number,
    h.title_respondent,
    h.respondent,
    h.respondent_family_name,
    h.respondent_given_name,
    h.respondent_address,
    h.respondent_phone_number,
    h.respondent_relationship,
    h.reporting_county,
    h.reporting_subcounty,
    h.reporting_health_facility,
    h.vaccine,
    h.vaccination_exists,
    h.vaccine_meningitis,
    h.vaccine_doses,
    h.vaccine_last_dose_date,
    h.vaccine_information_source,
    h.lumbar_puncture_date,
    h.lumbar_puncture_time,
    h.celebrospinal_fluid_appearance,
    h.inoculation_date,
    h.inoculation_time,
    h.sample_transport_medium,
    h.sample_transport_medium_others,
    h.laboratory_test_requested,
    h.reference_laboratory,
    h.laboratory_information_exists,
    h.laboratory_samples_collected,
    h.appearance_of_sttol_sample,
    h.laboratory_tests,
    h.laboratory_tests_other,
    h.title_results,
    h.leucocytes_results,
    h.pn_results,
    h.lymp_results,
    h.gram_results,
    h.rdt_results,
    h.serology_results,
    h.laboratory_results_other,
    h.date_of_laboratory_results,
    h.title_laboratory_facility,
    h.name_of_laboratory,
    h.patient_on_treatment,
    h.patient_on_treatment_specify,
    h.symptoms,
    h.date_of_onset,
    h.clinical_health_facility,
    h.name_of_health_facility,
    h.date_first_seen_at_facility,
    h.admission_date,
    h.patient_status,
    h.status_of_case,
    h.outcome_of_case,
    h.date_of_discharge,
    h.date_of_death,
    h.place_of_death,
    h.inpatient_number,
    h.outpatient_number,
    h.title_clinical_care,
    h.type_of_care,
    h.total,
    h.suspected,
    h.tested,
    h.confirmed,
    h.admitted,
    h.discharged,
    h.died,
    h.probable,
    h.contact,
    h.load_date
FROM combined_hierarchy h
