{{ config(
    materialized = 'table',
    indexes=[
      {'columns': ['syndrome']},
      {'columns': ['disease']},
      {'columns': ['id']},
      {'columns': ['parent_id']},
      {'columns': ['event_id']},
      {'columns': ['case_date']},
      {'columns': ['epi_week']},
      {'columns': ['type_of_case']},
      {'columns': ['country']},
      {'columns': ['county']},
      {'columns': ['subcounty']},
      {'columns': ['suspected']},
      {'columns': ['tested']},
      {'columns': ['confirmed']},
      {'columns': ['admitted']},
      {'columns': ['discharged']},
      {'columns': ['died']},
      {'columns': ['probable']},
      {'columns': ['contact']},
      {'columns': ['completed']},
      {'columns': ['hierarchy_level']},
      {'columns': ['has_children']}
    ]
)}}

WITH RECURSIVE

root_node AS (
    SELECT
        'a52f1b40-89b1-22df-a632-9dcf84b7c052'::text AS id,
        ''::text AS parent_id,
        0 AS hierarchy_level,
        'ROOT'::text AS contact_tree_label,
        NULL AS mform_id,
        NULL AS mform_event,
        NULL AS event_id,
        NULL AS form_id,
        NULL AS case_unique_id,
        'Draft'::text AS completed,
        NULL AS parent_completed,
        NULL AS created_role,
        NULL AS modified_role,
        NULL AS created_username,
        NULL AS created_timestamp,
        NULL AS modified_username,
        NULL AS modified_timestamp,
        NULL AS location_accuracy,
        NULL AS location_latitude,
        NULL AS location_longitude,
        NULL AS syndrome,
        'AFP'::text AS disease,
        null::date AS case_date,
        NULL AS epi_week,
        NULL AS epid,
        NULL AS date_of_investigation,
        NULL AS location_of_investigation,
        NULL AS location_of_investigation_other,
        NULL AS type_of_case,
        NULL AS given_name,
        NULL AS family_name,
        NULL AS sex,
        null::double precision AS age_years,
        null::double precision AS age_months,
        null::double precision AS age_days,
        NULL AS age_group,
        NULL AS date_of_birth,
        NULL AS country,
        NULL AS county,
        NULL AS subcounty,
        NULL AS ward,
        NULL AS case_is_pregnant,
        NULL AS marital_status,
        NULL AS phone_number,
        NULL AS occupation,
        NULL AS occupation_other,
        NULL AS title_residence,
        NULL AS case_has_insurance_cover,
        NULL AS type_of_residence,
        NULL AS town_village_camp,
        NULL AS landmark,
        NULL AS title_parent_guradian,
        NULL AS level_of_education,
        NULL AS guardian_family_name,
        NULL AS guardian_given_name,
        NULL AS guardian_phone_number,
        NULL AS title_respondent,
        NULL AS respondent,
        NULL AS respondent_family_name,
        NULL AS respondent_given_name,
        NULL AS respondent_address,
        NULL AS respondent_phone_number,
        NULL AS respondent_relationship,
        NULL AS date_of_onset,
        NULL AS fever_at_onset_of_paralysis,
        NULL AS progressive_paralysis,
        NULL AS paralysis_acute_and_flaccid,
        NULL AS paralysis_asymmetrical,
        NULL AS paralysis_site,
        NULL AS paralysis_site_other,
        NULL AS paralyzed_limb_sensitive_to_pain,
        NULL AS injection_before_paralysis,
        NULL AS injection_site,
        NULL AS provisional_diagnosis,
        NULL AS outcome,
        NULL AS total_vaccine_doses,
        NULL AS first_dose_date,
        NULL AS second_dose_date,
        NULL AS third_dose_date,
        NULL AS fourth_dose_date,
        NULL AS last_dose_date,
        NULL AS total_opv_sia_doses,
        NULL AS stool_condition,
        NULL AS date_final_culture_result_available,
        NULL AS date_specimen_received_in_ic_lab,
        NULL AS lab_id,
        NULL AS final_cell_culture_result,
        NULL AS date_results_sent_to_national_epi,
        NULL AS date_isolate_sent_by_national_laboratory_to_regional_laboratory,
        NULL AS date_itd_results_sent_by_regional_laboratory,
        NULL AS date_itd_results_received_by_county,
        NULL AS date_isolate_sent_for_sequencing,
        NULL AS date_final_results_sent_to_epi,
        NULL AS title_final_results,
        NULL AS w1_results,
        NULL AS w2_results,
        NULL AS w3_results,
        NULL AS discordant_sabin,
        NULL AS sl1_results,
        NULL AS sl2_results,
        NULL AS sl3_results,
        NULL AS vdpv1_results,
        NULL AS vdpv2_results,
        NULL AS vdpv3_results,
        NULL AS rnev_results,
        NULL AS rnpent_results,
        NULL AS date_first_specimen_collected,
        NULL AS date_second_specimen_collected,
        NULL AS date_specimen_sent_to_national,
        NULL AS date_specimen_received_at_national,
        NULL AS date_specimen_sent_to_lab,
        NULL AS immunocompromised_status_suspected,
        NULL AS afp_final_case_classification,
        NULL AS afp_vdpv_serotype,
        NULL AS place,
        NULL AS duration_months,
        NULL AS duration_days,
        NULL AS vaccine_administered,
        NULL AS date_of_vaccination,
        NULL AS total_vaccine_sia_doses,
        NULL AS vaccine_afp,
        NULL AS vaccine_afp_other,
        NULL AS number_of_doses,
        NULL AS date_of_last_dose,
        NULL AS vaccination_campaign,
        NULL AS source_of_vaccination_information,
        NULL AS source_of_vaccination_information_other,
        0::integer AS suspected,
        0::integer AS tested,
        0::integer AS confirmed,
        0::integer AS admitted,
        0::integer AS discharged,
        0::integer AS died,
        0::integer AS probable,
        0::integer AS contact,
        current_date AS load_date
),

hierarchy AS (
    SELECT * FROM root_node
    
    UNION ALL

    SELECT 
        c.id,
        CASE 
            WHEN c.parent_id IS NULL OR c.parent_id = '' THEN 'a52f1b40-89b1-22df-a632-9dcf84b7c052'
            ELSE c.parent_id
        END AS parent_id,
        h.hierarchy_level + 1 AS hierarchy_level,
        c.contact_tree_label,
        c.mform_id,
        c.mform_event,
        c.event_id,
        c.form_id,
        c.case_unique_id,
        c.completed,
        c.parent_completed,
        c.created_role,
        c.modified_role,
        c.created_username,
        c.created_timestamp,
        c.modified_username,
        c.modified_timestamp,
        c.location_accuracy,
        c.location_latitude,
        c.location_longitude,
        c.syndrome,
        c.disease,
        c.case_date,
        c.epi_week,
        c.epid,
        c.date_of_investigation,
        c.location_of_investigation,
        c.location_of_investigation_other,
        c.type_of_case,
        c.given_name,
        c.family_name,
        c.sex,
        c.age_years,
        c.age_months,
        c.age_days,
        c.age_group,
        c.date_of_birth,
        c.country,
        c.county,
        c.subcounty,
        c.ward,
        c.case_is_pregnant,
        c.marital_status,
        c.phone_number,
        c.occupation,
        c.occupation_other,
        c.title_residence,
        c.case_has_insurance_cover,
        c.type_of_residence,
        c.town_village_camp,
        c.landmark,
        c.title_parent_guradian,
        c.level_of_education,
        c.guardian_family_name,
        c.guardian_given_name,
        c.guardian_phone_number,
        c.title_respondent,
        c.respondent,
        c.respondent_family_name,
        c.respondent_given_name,
        c.respondent_address,
        c.respondent_phone_number,
        c.respondent_relationship,
        c.date_of_onset,
        c.fever_at_onset_of_paralysis,
        c.progressive_paralysis,
        c.paralysis_acute_and_flaccid,
        c.paralysis_asymmetrical,
        c.paralysis_site,
        c.paralysis_site_other,
        c.paralyzed_limb_sensitive_to_pain,
        c.injection_before_paralysis,
        c.injection_site,
        c.provisional_diagnosis,
        c.outcome,
        c.total_vaccine_doses,
        c.first_dose_date,
        c.second_dose_date,
        c.third_dose_date,
        c.fourth_dose_date,
        c.last_dose_date,
        c.total_opv_sia_doses,
        c.stool_condition,
        c.date_final_culture_result_available,
        c.date_specimen_received_in_ic_lab,
        c.lab_id,
        c.final_cell_culture_result,
        c.date_results_sent_to_national_epi,
        c.date_isolate_sent_by_national_laboratory_to_regional_laboratory,
        c.date_itd_results_sent_by_regional_laboratory,
        c.date_itd_results_received_by_county,
        c.date_isolate_sent_for_sequencing,
        c.date_final_results_sent_to_epi,
        c.title_final_results,
        c.w1_results,
        c.w2_results,
        c.w3_results,
        c.discordant_sabin,
        c.sl1_results,
        c.sl2_results,
        c.sl3_results,
        c.vdpv1_results,
        c.vdpv2_results,
        c.vdpv3_results,
        c.rnev_results,
        c.rnpent_results,
        c.date_first_specimen_collected,
        c.date_second_specimen_collected,
        c.date_specimen_sent_to_national,
        c.date_specimen_received_at_national,
        c.date_specimen_sent_to_lab,
        c.immunocompromised_status_suspected,
        c.afp_final_case_classification,
        c.afp_vdpv_serotype,
        c.place,
        c.duration_months,
        c.duration_days,
        c.vaccine_administered,
        c.date_of_vaccination,
        c.total_vaccine_sia_doses,
        c.vaccine_afp,
        c.vaccine_afp_other,
        c.number_of_doses,
        c.date_of_last_dose,
        c.vaccination_campaign,
        c.source_of_vaccination_information,
        c.source_of_vaccination_information_other,
        (1)::integer AS suspected,
        (CASE WHEN c.date_first_specimen_collected IS NOT NULL THEN 1 ELSE 0 END)::integer AS tested,
        (CASE WHEN c.afp_final_case_classification = 'Confirmed' THEN 1 WHEN c.type_of_case = 'Confirmed' THEN 1 ELSE 0 END)::integer AS confirmed,
        (CASE WHEN c.outcome = 'Admitted' THEN 1 ELSE 0 END)::integer AS admitted,
        (CASE WHEN c.outcome = 'Discharged' THEN 1 ELSE 0 END)::integer AS discharged,
        (CASE WHEN c.outcome = 'Dead' THEN 1 ELSE 0 END)::integer AS died,
        (CASE WHEN c.type_of_case = 'Probable' THEN 1 ELSE 0 END)::integer AS probable,
        (CASE WHEN c.type_of_case = 'Contact' THEN 1 ELSE 0 END)::integer AS contact,
        current_date AS load_date
    FROM {{ ref('int_acute_flaccid_paralysis') }} c
    INNER JOIN hierarchy h ON 
        CASE 
            WHEN c.parent_id IS NULL OR c.parent_id = '' THEN 'a52f1b40-89b1-22df-a632-9dcf84b7c052'
            ELSE c.parent_id
        END = h.id
    WHERE NOT (c.id = 'a52f1b40-89b1-22df-a632-9dcf84b7c052')
),

first_level_orphans AS (
    SELECT 
        c.id,
        'a52f1b40-89b1-22df-a632-9dcf84b7c052' AS parent_id,
        1 AS hierarchy_level,
        c.contact_tree_label,
        c.mform_id,
        c.mform_event,
        c.event_id,
        c.form_id,
        c.case_unique_id,
        c.completed,
        c.parent_completed,
        c.created_role,
        c.modified_role,
        c.created_username,
        c.created_timestamp,
        c.modified_username,
        c.modified_timestamp,
        c.location_accuracy,
        c.location_latitude,
        c.location_longitude,
        c.syndrome,
        c.disease,
        c.case_date,
        c.epi_week,
        c.epid,
        c.date_of_investigation,
        c.location_of_investigation,
        c.location_of_investigation_other,
        c.type_of_case,
        c.given_name,
        c.family_name,
        c.sex,
        c.age_years,
        c.age_months,
        c.age_days,
        c.age_group,
        c.date_of_birth,
        c.country,
        c.county,
        c.subcounty,
        c.ward,
        c.case_is_pregnant,
        c.marital_status,
        c.phone_number,
        c.occupation,
        c.occupation_other,
        c.title_residence,
        c.case_has_insurance_cover,
        c.type_of_residence,
        c.town_village_camp,
        c.landmark,
        c.title_parent_guradian,
        c.level_of_education,
        c.guardian_family_name,
        c.guardian_given_name,
        c.guardian_phone_number,
        c.title_respondent,
        c.respondent,
        c.respondent_family_name,
        c.respondent_given_name,
        c.respondent_address,
        c.respondent_phone_number,
        c.respondent_relationship,
        c.date_of_onset,
        c.fever_at_onset_of_paralysis,
        c.progressive_paralysis,
        c.paralysis_acute_and_flaccid,
        c.paralysis_asymmetrical,
        c.paralysis_site,
        c.paralysis_site_other,
        c.paralyzed_limb_sensitive_to_pain,
        c.injection_before_paralysis,
        c.injection_site,
        c.provisional_diagnosis,
        c.outcome,
        c.total_vaccine_doses,
        c.first_dose_date,
        c.second_dose_date,
        c.third_dose_date,
        c.fourth_dose_date,
        c.last_dose_date,
        c.total_opv_sia_doses,
        c.stool_condition,
        c.date_final_culture_result_available,
        c.date_specimen_received_in_ic_lab,
        c.lab_id,
        c.final_cell_culture_result,
        c.date_results_sent_to_national_epi,
        c.date_isolate_sent_by_national_laboratory_to_regional_laboratory,
        c.date_itd_results_sent_by_regional_laboratory,
        c.date_itd_results_received_by_county,
        c.date_isolate_sent_for_sequencing,
        c.date_final_results_sent_to_epi,
        c.title_final_results,
        c.w1_results,
        c.w2_results,
        c.w3_results,
        c.discordant_sabin,
        c.sl1_results,
        c.sl2_results,
        c.sl3_results,
        c.vdpv1_results,
        c.vdpv2_results,
        c.vdpv3_results,
        c.rnev_results,
        c.rnpent_results,
        c.date_first_specimen_collected,
        c.date_second_specimen_collected,
        c.date_specimen_sent_to_national,
        c.date_specimen_received_at_national,
        c.date_specimen_sent_to_lab,
        c.immunocompromised_status_suspected,
        c.afp_final_case_classification,
        c.afp_vdpv_serotype,
        c.place,
        c.duration_months,
        c.duration_days,
        c.vaccine_administered,
        c.date_of_vaccination,
        c.total_vaccine_sia_doses,
        c.vaccine_afp,
        c.vaccine_afp_other,
        c.number_of_doses,
        c.date_of_last_dose,
        c.vaccination_campaign,
        c.source_of_vaccination_information,
        c.source_of_vaccination_information_other,
        (1)::integer AS suspected,
        (CASE WHEN c.date_first_specimen_collected IS NOT NULL THEN 1 ELSE 0 END)::integer AS tested,
        (CASE WHEN c.afp_final_case_classification = 'Confirmed' THEN 1 WHEN c.type_of_case = 'Confirmed' THEN 1 ELSE 0 END)::integer AS confirmed,
        (CASE WHEN c.outcome = 'Admitted' THEN 1 ELSE 0 END)::integer AS admitted,
        (CASE WHEN c.outcome = 'Discharged' THEN 1 ELSE 0 END)::integer AS discharged,
        (CASE WHEN c.outcome = 'Dead' THEN 1 ELSE 0 END)::integer AS died,
        (CASE WHEN c.type_of_case = 'Probable' THEN 1 ELSE 0 END)::integer AS probable,
        (CASE WHEN c.type_of_case = 'Contact' THEN 1 ELSE 0 END)::integer AS contact,
        current_date AS load_date
    FROM {{ ref('int_acute_flaccid_paralysis') }} c
    LEFT JOIN hierarchy h ON c.parent_id = h.id
    WHERE h.id IS NULL 
      AND c.parent_id IS NOT NULL 
      AND c.parent_id != '' 
      AND c.id != 'a52f1b40-89b1-22df-a632-9dcf84b7c052'
),

combined_hierarchy AS (
    SELECT * FROM hierarchy
    UNION ALL
    SELECT * FROM first_level_orphans
)

SELECT
    h.id,
    h.parent_id,
    h.hierarchy_level,
    CASE 
        WHEN EXISTS (
            SELECT 1 
            FROM {{ ref('int_acute_flaccid_paralysis') }} child 
            WHERE child.parent_id = h.id
        ) THEN true
        ELSE false
    END as has_children,
    h.contact_tree_label,
    h.mform_id,
    h.mform_event,
    h.event_id,
    h.form_id,
    h.case_unique_id,
    h.completed,
    h.parent_completed,
    h.created_role,
    h.modified_role,
    h.created_username,
    h.created_timestamp,
    h.modified_username,
    h.modified_timestamp,
    h.location_accuracy,
    h.location_latitude,
    h.location_longitude,
    h.syndrome,
    'AFP'::text AS disease,
    h.case_date,
    h.epi_week,
    h.epid,
    h.date_of_investigation,
    h.location_of_investigation,
    h.location_of_investigation_other,
    CASE WHEN h.type_of_case IS NOT NULL THEN h.type_of_case ELSE 'Unknown' END AS type_of_case,
    h.given_name,
    h.family_name,
    h.sex,
    h.age_years,
    h.age_months,
    h.age_days,
    h.age_group,
    h.date_of_birth,
    h.country,
    h.county,
    h.subcounty,
    h.ward,
    h.case_is_pregnant,
    h.marital_status,
    h.phone_number,
    h.occupation,
    h.occupation_other,
    h.title_residence,
    h.case_has_insurance_cover,
    h.type_of_residence,
    h.town_village_camp,
    h.landmark,
    h.title_parent_guradian,
    h.level_of_education,
    h.guardian_family_name,
    h.guardian_given_name,
    h.guardian_phone_number,
    h.title_respondent,
    h.respondent,
    h.respondent_family_name,
    h.respondent_given_name,
    h.respondent_address,
    h.respondent_phone_number,
    h.respondent_relationship,
    h.date_of_onset,
    h.fever_at_onset_of_paralysis,
    h.progressive_paralysis,
    h.paralysis_acute_and_flaccid,
    h.paralysis_asymmetrical,
    h.paralysis_site,
    h.paralysis_site_other,
    h.paralyzed_limb_sensitive_to_pain,
    h.injection_before_paralysis,
    h.injection_site,
    h.provisional_diagnosis,
    h.outcome,
    h.total_vaccine_doses,
    h.first_dose_date,
    h.second_dose_date,
    h.third_dose_date,
    h.fourth_dose_date,
    h.last_dose_date,
    h.total_opv_sia_doses,
    h.stool_condition,
    h.date_final_culture_result_available,
    h.date_specimen_received_in_ic_lab,
    h.lab_id,
    h.final_cell_culture_result,
    h.date_results_sent_to_national_epi,
    h.date_isolate_sent_by_national_laboratory_to_regional_laboratory,
    h.date_itd_results_sent_by_regional_laboratory,
    h.date_itd_results_received_by_county,
    h.date_isolate_sent_for_sequencing,
    h.date_final_results_sent_to_epi,
    h.title_final_results,
    h.w1_results,
    h.w2_results,
    h.w3_results,
    h.discordant_sabin,
    h.sl1_results,
    h.sl2_results,
    h.sl3_results,
    h.vdpv1_results,
    h.vdpv2_results,
    h.vdpv3_results,
    h.rnev_results,
    h.rnpent_results,
    h.date_first_specimen_collected,
    h.date_second_specimen_collected,
    h.date_specimen_sent_to_national,
    h.date_specimen_received_at_national,
    h.date_specimen_sent_to_lab,
    h.immunocompromised_status_suspected,
    h.afp_final_case_classification,
    h.afp_vdpv_serotype,
    h.place,
    h.duration_months,
    h.duration_days,
    h.vaccine_administered,
    h.date_of_vaccination,
    h.total_vaccine_sia_doses,
    h.vaccine_afp,
    h.vaccine_afp_other,
    h.number_of_doses,
    h.date_of_last_dose,
    h.vaccination_campaign,
    h.source_of_vaccination_information,
    h.source_of_vaccination_information_other,
    h.suspected,
    h.tested,
    h.confirmed,
    h.admitted,
    h.discharged,
    h.died,
    h.probable,
    h.contact,
    h.load_date
FROM combined_hierarchy h
