{{ config(
    materialized = 'table',
    indexes=[
      {'columns': ['syndrome']},
      {'columns': ['disease']},
      {'columns': ['id']},
      {'columns': ['parent_id']},
      {'columns': ['event_id']},
      {'columns': ['case_date']},
      {'columns': ['epi_week']},
      {'columns': ['type_of_case']},
      {'columns': ['country']},
      {'columns': ['county']},
      {'columns': ['subcounty']},
      {'columns': ['total']},
      {'columns': ['suspected']},
      {'columns': ['tested']},
      {'columns': ['confirmed']},
      {'columns': ['admitted']},
      {'columns': ['discharged']},
      {'columns': ['died']},
      {'columns': ['probable']},
      {'columns': ['contact']},
      {'columns': ['completed']},
      {'columns': ['hierarchy_level']},
      {'columns': ['has_children']}
    ]
)}}

WITH RECURSIVE

root_node AS (
    SELECT
        'a52f1b40-89b1-22df-a632-9dcf84b7c051'::text AS id,
        ''::text AS parent_id,
        0 AS hierarchy_level,
        'ROOT'::text AS contact_tree_label,
        NULL AS mform_id,
        NULL AS mform_event,
        NULL AS event_id,
        NULL AS form_id,
        NULL AS case_unique_id,
        'Draft'::text AS completed,
        NULL AS parent_completed,
        NULL AS created_role,
        NULL AS modified_role,
        NULL AS created_username,
        NULL AS created_timestamp,
        NULL AS modified_username,
        NULL AS modified_timestamp,
        NULL AS location_accuracy,
        NULL AS location_latitude,
        NULL AS location_longitude,
        NULL AS syndrome,
        'Monkey Pox'::text AS disease,
        null::date AS case_date,
        NULL AS epi_week,
        NULL AS epid,
        NULL AS date_of_investigation,
        NULL AS location_of_investigation,
        NULL AS location_of_investigation_other,
        NULL AS type_of_case,
        NULL AS family_name,
        NULL AS given_name,
        NULL AS sex,
        null::double precision AS age_years,
        null::double precision AS age_months,
        null::double precision AS age_days,
        NULL AS age_group,
        NULL AS date_of_birth,
        NULL AS pregnant,
        NULL AS phone_number,
        NULL AS occupation,
        NULL AS occupation_other,
        NULL AS title_residence,
        NULL AS type_of_residence,
        NULL AS country,
        NULL AS county,
        NULL AS subcounty,
        NULL AS ward,
        NULL AS town_village_camp,
        NULL AS landmark,
        NULL AS marital_status,
        NULL AS level_of_education,
        NULL AS case_has_insurance_cover,
        NULL AS title_parent_guradian,
        NULL AS guardian_family_name,
        NULL AS guardian_given_name,
        NULL AS guardian_phone_number,
        NULL AS title_respondent,
        NULL AS respondent,
        NULL AS respondent_family_name,
        NULL AS respondent_given_name,
        NULL AS respondent_address,
        NULL AS respondent_phone_number,
        NULL AS respondent_relationship,
        NULL AS symptoms,
        NULL AS symptoms_other,
        NULL AS fever_temperature,
        NULL AS locations_of_lymphadenopathy,
        NULL AS date_of_onset,
        NULL AS start_location_of_rash,
        NULL AS start_location_of_rash_other,
        NULL AS spread_location_of_rash,
        NULL AS spread_location_of_rash_other,
        NULL AS number_of_lesions,
        NULL AS development_of_rash,
        NULL AS distribution_of_rash,
        NULL AS history_of_immunosuppressive_conditions,
        NULL AS hiv_positive,
        NULL AS date_of_hiv_diagnosis,
        NULL AS patient_on_art,
        NULL AS history_of_skin_disease,
        NULL AS recently_given_birth,
        NULL AS baby_is_symptomatic,
        NULL AS case_is_breatfeeding,
        NULL AS case_was_breastfeeding_three_weeks_prior_to_illness,
        NULL AS title_clinical_care,
        NULL AS type_of_care,
        NULL AS case_is_isolated,
        NULL AS health_facility_name,
        NULL AS reason_for_hospitalization,
        NULL AS reason_for_hospitalization_other,
        NULL AS date_of_admission,
        NULL AS inpatient_number,
        NULL AS date_first_seen_at_facility,
        NULL AS outpatient_number,
        NULL AS treatment_given,
        NULL AS treatment_given_other,
        NULL AS outcome_of_patient,
        NULL AS status_of_patient,
        NULL AS date_of_discharge,
        NULL AS date_of_death,
        NULL AS place_of_death,
        NULL AS food_name,
        NULL AS food_source,
        NULL AS food_consumption_date,
        NULL AS food_participants_count,
        NULL AS food_affected_participants_count,
        NULL AS water_sources,
        NULL AS water_sources_other,
        NULL AS toilet_types,
        NULL AS toilet_types_other,
        NULL AS travel_origin_country,
        NULL AS travel_origin_city,
        NULL AS travel_departure_date,
        NULL AS travel_destination_country,
        NULL AS travel_destination_city,
        NULL AS travel_arrival_date,
        NULL AS animal_exposure_location,
        NULL AS type_of_exposure,
        NULL AS type_of_contact,
        NULL AS contact_was_symptomatic,
        NULL AS date_of_contact,
        NULL AS frequency_of_contact,
        NULL AS duration_of_contact,
        NULL AS location_of_contact,
        NULL AS location_of_contact_other,
        NULL AS relationship_of_contact,
        NULL AS relationship_of_contact_other,
        NULL AS title_ppe,
        NULL AS case_was_wearing_ppe,
        NULL AS ppe_items_worn,
        NULL AS ppe_breach,
        NULL AS hand_hygiene_before_wearing_ppe,
        NULL AS hand_hygiene_after_wearing_ppe,
        NULL AS animal_species,
        NULL AS animal_species_other,
        NULL AS animal_exposure,
        NULL AS animal_exposure_other,
        NULL AS date_of_exposure,
        NULL AS case_was_ill,
        NULL AS description_of_event,
        NULL AS location_of_event,
        NULL AS date_of_event,
        NULL AS description_of_illness,
        NULL AS type_of_direct_contact,
        NULL AS type_of_direct_contact_other,
        NULL AS samples_were_collected,
        NULL AS samples_collected,
        NULL AS samples_collected_other,
        NULL AS date_of_sample_collection,
        NULL AS tests,
        NULL AS test_other,
        NULL AS result_of_laboratory_test,
        NULL AS date_of_laboratory_testing_results,
        NULL AS facility_name,
        NULL AS facility_name_other,
        NULL AS clade_of_mpox,
        NULL AS day_of_follow_up,
        NULL AS date_of_follow_up,
        NULL AS contact_is_symptomatic,
        NULL AS smallpox_mpox_vaccine_received,
        NULL AS number_of_doses,
        NULL AS date_of_first_dose,
        NULL AS date_of_last_dose,
        NULL AS brand_of_vaccine,
        NULL AS brand_of_vaccine_other,
        NULL AS route_of_admission,
        NULL AS route_of_admission_other,
        NULL AS reason_for_vaccination,
        0::integer AS total,
        0::integer AS suspected,
        0::integer AS tested,
        0::integer AS confirmed,
        0::integer AS admitted,
        0::integer AS discharged,
        0::integer AS died,
        0::integer AS probable,
        0::integer AS contact,
        current_date AS load_date
),

hierarchy AS (
    SELECT * FROM root_node
    
    UNION ALL

    SELECT 
        c.id,
        CASE 
            WHEN c.parent_id IS NULL OR c.parent_id = '' THEN 'a52f1b40-89b1-22df-a632-9dcf84b7c051'
            ELSE c.parent_id
        END AS parent_id,
        h.hierarchy_level + 1 AS hierarchy_level,
        c.contact_tree_label,
        c.mform_id,
        c.mform_event,
        c.event_id,
        c.form_id,
        c.case_unique_id,
        c.completed,
        c.parent_completed,
        c.created_role,
        c.modified_role,
        c.created_username,
        c.created_timestamp,
        c.modified_username,
        c.modified_timestamp,
        c.location_accuracy,
        c.location_latitude,
        c.location_longitude,
        c.syndrome,
        c.disease,
        c.case_date,
        c.epi_week,
        c.epid,
        c.date_of_investigation,
        c.location_of_investigation,
        c.location_of_investigation_other,
        c.type_of_case,
        c.family_name,
        c.given_name,
        c.sex,
        c.age_years,
        c.age_months,
        c.age_days,
        c.age_group,
        c.date_of_birth,
        c.pregnant,
        c.phone_number,
        c.occupation,
        c.occupation_other,
        c.title_residence,
        c.type_of_residence,
        c.country,
        c.county,
        c.subcounty,
        c.ward,
        c.town_village_camp,
        c.landmark,
        c.marital_status,
        c.level_of_education,
        c.case_has_insurance_cover,
        c.title_parent_guradian,
        c.guardian_family_name,
        c.guardian_given_name,
        c.guardian_phone_number,
        c.title_respondent,
        c.respondent,
        c.respondent_family_name,
        c.respondent_given_name,
        c.respondent_address,
        c.respondent_phone_number,
        c.respondent_relationship,
        c.symptoms,
        c.symptoms_other,
        c.fever_temperature,
        c.locations_of_lymphadenopathy,
        c.date_of_onset,
        c.start_location_of_rash,
        c.start_location_of_rash_other,
        c.spread_location_of_rash,
        c.spread_location_of_rash_other,
        c.number_of_lesions,
        c.development_of_rash,
        c.distribution_of_rash,
        c.history_of_immunosuppressive_conditions,
        c.hiv_positive,
        c.date_of_hiv_diagnosis,
        c.patient_on_art,
        c.history_of_skin_disease,
        c.recently_given_birth,
        c.baby_is_symptomatic,
        c.case_is_breatfeeding,
        c.case_was_breastfeeding_three_weeks_prior_to_illness,
        c.title_clinical_care,
        c.type_of_care,
        c.case_is_isolated,
        c.health_facility_name,
        c.reason_for_hospitalization,
        c.reason_for_hospitalization_other,
        c.date_of_admission,
        c.inpatient_number,
        c.date_first_seen_at_facility,
        c.outpatient_number,
        c.treatment_given,
        c.treatment_given_other,
        c.outcome_of_patient,
        c.status_of_patient,
        c.date_of_discharge,
        c.date_of_death,
        c.place_of_death,
        c.food_name,
        c.food_source,
        c.food_consumption_date,
        c.food_participants_count,
        c.food_affected_participants_count,
        c.water_sources,
        c.water_sources_other,
        c.toilet_types,
        c.toilet_types_other,
        c.travel_origin_country,
        c.travel_origin_city,
        c.travel_departure_date,
        c.travel_destination_country,
        c.travel_destination_city,
        c.travel_arrival_date,
        c.animal_exposure_location,
        c.type_of_exposure,
        c.type_of_contact,
        c.contact_was_symptomatic,
        c.date_of_contact,
        c.frequency_of_contact,
        c.duration_of_contact,
        c.location_of_contact,
        c.location_of_contact_other,
        c.relationship_of_contact,
        c.relationship_of_contact_other,
        c.title_ppe,
        c.case_was_wearing_ppe,
        c.ppe_items_worn,
        c.ppe_breach,
        c.hand_hygiene_before_wearing_ppe,
        c.hand_hygiene_after_wearing_ppe,
        c.animal_species,
        c.animal_species_other,
        c.animal_exposure,
        c.animal_exposure_other,
        c.date_of_exposure,
        c.case_was_ill,
        c.description_of_event,
        c.location_of_event,
        c.date_of_event,
        c.description_of_illness,
        c.type_of_direct_contact,
        c.type_of_direct_contact_other,
        c.samples_were_collected,
        c.samples_collected,
        c.samples_collected_other,
        c.date_of_sample_collection,
        c.tests,
        c.test_other,
        c.result_of_laboratory_test,
        c.date_of_laboratory_testing_results,
        c.facility_name,
        c.facility_name_other,
        c.clade_of_mpox,
        c.day_of_follow_up,
        c.date_of_follow_up,
        c.contact_is_symptomatic,
        c.smallpox_mpox_vaccine_received,
        c.number_of_doses,
        c.date_of_first_dose,
        c.date_of_last_dose,
        c.brand_of_vaccine,
        c.brand_of_vaccine_other,
        c.route_of_admission,
        c.route_of_admission_other,
        c.reason_for_vaccination,
        (1)::integer AS total,
        (1)::integer AS suspected,
        (CASE WHEN c.tests IS NOT NULL THEN 1 WHEN c.test_other IS NOT NULL THEN 1 ELSE 0 END)::integer AS tested,
        (CASE WHEN c.result_of_laboratory_test = 'Positive' THEN 1 WHEN c.type_of_case = 'Confirmed' THEN 1 ELSE 0 END)::integer AS confirmed,
        (CASE WHEN c.outcome_of_patient = 'Admitted' THEN 1 WHEN c.status_of_patient = 'Admitted' THEN 1 ELSE 0 END)::integer AS admitted,
        (CASE WHEN c.outcome_of_patient = 'Discharged' THEN 1 WHEN c.status_of_patient = 'Discharged' THEN 1 ELSE 0 END)::integer AS discharged,
        (CASE WHEN c.outcome_of_patient = 'Dead' THEN 1 ELSE 0 END)::integer AS died,
        (CASE WHEN c.type_of_case = 'Probable' THEN 1 ELSE 0 END)::integer AS probable,
        (CASE WHEN c.type_of_case = 'Contact' THEN 1 ELSE 0 END)::integer AS contact,
        current_date AS load_date
    FROM {{ ref('int_mpox') }} c
    INNER JOIN hierarchy h ON 
        CASE 
            WHEN c.parent_id IS NULL OR c.parent_id = '' THEN 'a52f1b40-89b1-22df-a632-9dcf84b7c051'
            ELSE c.parent_id
        END = h.id
    WHERE NOT (c.id = 'a52f1b40-89b1-22df-a632-9dcf84b7c051')
),

first_level_orphans AS (
    SELECT 
        c.id,
        'a52f1b40-89b1-22df-a632-9dcf84b7c051' AS parent_id,
        1 AS hierarchy_level,
        c.contact_tree_label,
        c.mform_id,
        c.mform_event,
        c.event_id,
        c.form_id,
        c.case_unique_id,
        c.completed,
        c.parent_completed,
        c.created_role,
        c.modified_role,
        c.created_username,
        c.created_timestamp,
        c.modified_username,
        c.modified_timestamp,
        c.location_accuracy,
        c.location_latitude,
        c.location_longitude,
        c.syndrome,
        c.disease,
        c.case_date,
        c.epi_week,
        c.epid,
        c.date_of_investigation,
        c.location_of_investigation,
        c.location_of_investigation_other,
        c.type_of_case,
        c.family_name,
        c.given_name,
        c.sex,
        c.age_years,
        c.age_months,
        c.age_days,
        c.age_group,
        c.date_of_birth,
        c.pregnant,
        c.phone_number,
        c.occupation,
        c.occupation_other,
        c.title_residence,
        c.type_of_residence,
        c.country,
        c.county,
        c.subcounty,
        c.ward,
        c.town_village_camp,
        c.landmark,
        c.marital_status,
        c.level_of_education,
        c.case_has_insurance_cover,
        c.title_parent_guradian,
        c.guardian_family_name,
        c.guardian_given_name,
        c.guardian_phone_number,
        c.title_respondent,
        c.respondent,
        c.respondent_family_name,
        c.respondent_given_name,
        c.respondent_address,
        c.respondent_phone_number,
        c.respondent_relationship,
        c.symptoms,
        c.symptoms_other,
        c.fever_temperature,
        c.locations_of_lymphadenopathy,
        c.date_of_onset,
        c.start_location_of_rash,
        c.start_location_of_rash_other,
        c.spread_location_of_rash,
        c.spread_location_of_rash_other,
        c.number_of_lesions,
        c.development_of_rash,
        c.distribution_of_rash,
        c.history_of_immunosuppressive_conditions,
        c.hiv_positive,
        c.date_of_hiv_diagnosis,
        c.patient_on_art,
        c.history_of_skin_disease,
        c.recently_given_birth,
        c.baby_is_symptomatic,
        c.case_is_breatfeeding,
        c.case_was_breastfeeding_three_weeks_prior_to_illness,
        c.title_clinical_care,
        c.type_of_care,
        c.case_is_isolated,
        c.health_facility_name,
        c.reason_for_hospitalization,
        c.reason_for_hospitalization_other,
        c.date_of_admission,
        c.inpatient_number,
        c.date_first_seen_at_facility,
        c.outpatient_number,
        c.treatment_given,
        c.treatment_given_other,
        c.outcome_of_patient,
        c.status_of_patient,
        c.date_of_discharge,
        c.date_of_death,
        c.place_of_death,
        c.food_name,
        c.food_source,
        c.food_consumption_date,
        c.food_participants_count,
        c.food_affected_participants_count,
        c.water_sources,
        c.water_sources_other,
        c.toilet_types,
        c.toilet_types_other,
        c.travel_origin_country,
        c.travel_origin_city,
        c.travel_departure_date,
        c.travel_destination_country,
        c.travel_destination_city,
        c.travel_arrival_date,
        c.animal_exposure_location,
        c.type_of_exposure,
        c.type_of_contact,
        c.contact_was_symptomatic,
        c.date_of_contact,
        c.frequency_of_contact,
        c.duration_of_contact,
        c.location_of_contact,
        c.location_of_contact_other,
        c.relationship_of_contact,
        c.relationship_of_contact_other,
        c.title_ppe,
        c.case_was_wearing_ppe,
        c.ppe_items_worn,
        c.ppe_breach,
        c.hand_hygiene_before_wearing_ppe,
        c.hand_hygiene_after_wearing_ppe,
        c.animal_species,
        c.animal_species_other,
        c.animal_exposure,
        c.animal_exposure_other,
        c.date_of_exposure,
        c.case_was_ill,
        c.description_of_event,
        c.location_of_event,
        c.date_of_event,
        c.description_of_illness,
        c.type_of_direct_contact,
        c.type_of_direct_contact_other,
        c.samples_were_collected,
        c.samples_collected,
        c.samples_collected_other,
        c.date_of_sample_collection,
        c.tests,
        c.test_other,
        c.result_of_laboratory_test,
        c.date_of_laboratory_testing_results,
        c.facility_name,
        c.facility_name_other,
        c.clade_of_mpox,
        c.day_of_follow_up,
        c.date_of_follow_up,
        c.contact_is_symptomatic,
        c.smallpox_mpox_vaccine_received,
        c.number_of_doses,
        c.date_of_first_dose,
        c.date_of_last_dose,
        c.brand_of_vaccine,
        c.brand_of_vaccine_other,
        c.route_of_admission,
        c.route_of_admission_other,
        c.reason_for_vaccination,
        (1)::integer AS total,
        (1)::integer AS suspected,
        (CASE WHEN c.tests IS NOT NULL THEN 1 WHEN c.test_other IS NOT NULL THEN 1 ELSE 0 END)::integer AS tested,
        (CASE WHEN c.result_of_laboratory_test = 'Positive' THEN 1 WHEN c.type_of_case = 'Confirmed' THEN 1 ELSE 0 END)::integer AS confirmed,
        (CASE WHEN c.outcome_of_patient = 'Admitted' THEN 1 WHEN c.status_of_patient = 'Admitted' THEN 1 ELSE 0 END)::integer AS admitted,
        (CASE WHEN c.outcome_of_patient = 'Discharged' THEN 1 WHEN c.status_of_patient = 'Discharged' THEN 1 ELSE 0 END)::integer AS discharged,
        (CASE WHEN c.outcome_of_patient = 'Dead' THEN 1 ELSE 0 END)::integer AS died,
        (CASE WHEN c.type_of_case = 'Probable' THEN 1 ELSE 0 END)::integer AS probable,
        (CASE WHEN c.type_of_case = 'Contact' THEN 1 ELSE 0 END)::integer AS contact,
        current_date AS load_date
    FROM {{ ref('int_mpox') }} c
    LEFT JOIN hierarchy h ON c.parent_id = h.id
    WHERE h.id IS NULL 
      AND c.parent_id IS NOT NULL 
      AND c.parent_id != '' 
      AND c.id != 'a52f1b40-89b1-22df-a632-9dcf84b7c051'
),

combined_hierarchy AS (
    SELECT * FROM hierarchy
    UNION ALL
    SELECT * FROM first_level_orphans
)

SELECT
    h.id,
    h.parent_id,
    h.hierarchy_level,
    CASE 
        WHEN EXISTS (
            SELECT 1 
            FROM {{ ref('int_mpox') }} child 
            WHERE child.parent_id = h.id
        ) THEN true
        ELSE false
    END as has_children,
    h.contact_tree_label,
    h.mform_id,
    h.mform_event,
    h.event_id,
    h.form_id,
    h.case_unique_id,
    h.completed,
    h.parent_completed,
    h.created_role,
    h.modified_role,
    h.created_username,
    h.created_timestamp,
    h.modified_username,
    h.modified_timestamp,
    h.location_accuracy,
    h.location_latitude,
    h.location_longitude,
    h.syndrome,
    'Monkey Pox'::text AS disease,
    h.case_date,
    h.epi_week,
    h.epid,
    h.date_of_investigation,
    h.location_of_investigation,
    h.location_of_investigation_other,
    h.type_of_case,
    h.family_name,
    h.given_name,
    h.sex,
    h.age_years,
    h.age_months,
    h.age_days,
    h.age_group,
    h.date_of_birth,
    h.pregnant,
    h.phone_number,
    h.occupation,
    h.occupation_other,
    h.title_residence,
    h.type_of_residence,
    h.country,
    h.county,
    h.subcounty,
    h.ward,
    h.town_village_camp,
    h.landmark,
    h.marital_status,
    h.level_of_education,
    h.case_has_insurance_cover,
    h.title_parent_guradian,
    h.guardian_family_name,
    h.guardian_given_name,
    h.guardian_phone_number,
    h.title_respondent,
    h.respondent,
    h.respondent_family_name,
    h.respondent_given_name,
    h.respondent_address,
    h.respondent_phone_number,
    h.respondent_relationship,
    h.symptoms,
    h.symptoms_other,
    h.fever_temperature,
    h.locations_of_lymphadenopathy,
    h.date_of_onset,
    h.start_location_of_rash,
    h.start_location_of_rash_other,
    h.spread_location_of_rash,
    h.spread_location_of_rash_other,
    h.number_of_lesions,
    h.development_of_rash,
    h.distribution_of_rash,
    h.history_of_immunosuppressive_conditions,
    h.hiv_positive,
    h.date_of_hiv_diagnosis,
    h.patient_on_art,
    h.history_of_skin_disease,
    h.recently_given_birth,
    h.baby_is_symptomatic,
    h.case_is_breatfeeding,
    h.case_was_breastfeeding_three_weeks_prior_to_illness,
    h.title_clinical_care,
    h.type_of_care,
    h.case_is_isolated,
    h.health_facility_name,
    h.reason_for_hospitalization,
    h.reason_for_hospitalization_other,
    h.date_of_admission,
    h.inpatient_number,
    h.date_first_seen_at_facility,
    h.outpatient_number,
    h.treatment_given,
    h.treatment_given_other,
    h.outcome_of_patient,
    h.status_of_patient,
    h.date_of_discharge,
    h.date_of_death,
    h.place_of_death,
    h.food_name,
    h.food_source,
    h.food_consumption_date,
    h.food_participants_count,
    h.food_affected_participants_count,
    h.water_sources,
    h.water_sources_other,
    h.toilet_types,
    h.toilet_types_other,
    h.travel_origin_country,
    h.travel_origin_city,
    h.travel_departure_date,
    h.travel_destination_country,
    h.travel_destination_city,
    h.travel_arrival_date,
    h.animal_exposure_location,
    h.type_of_exposure,
    h.type_of_contact,
    h.contact_was_symptomatic,
    h.date_of_contact,
    h.frequency_of_contact,
    h.duration_of_contact,
    h.location_of_contact,
    h.location_of_contact_other,
    h.relationship_of_contact,
    h.relationship_of_contact_other,
    h.title_ppe,
    h.case_was_wearing_ppe,
    h.ppe_items_worn,
    h.ppe_breach,
    h.hand_hygiene_before_wearing_ppe,
    h.hand_hygiene_after_wearing_ppe,
    h.animal_species,
    h.animal_species_other,
    h.animal_exposure,
    h.animal_exposure_other,
    h.date_of_exposure,
    h.case_was_ill,
    h.description_of_event,
    h.location_of_event,
    h.date_of_event,
    h.description_of_illness,
    h.type_of_direct_contact,
    h.type_of_direct_contact_other,
    h.samples_were_collected,
    h.samples_collected,
    h.samples_collected_other,
    h.date_of_sample_collection,
    h.tests,
    h.test_other,
    h.result_of_laboratory_test,
    h.date_of_laboratory_testing_results,
    h.facility_name,
    h.facility_name_other,
    h.clade_of_mpox,
    h.day_of_follow_up,
    h.date_of_follow_up,
    h.contact_is_symptomatic,
    h.smallpox_mpox_vaccine_received,
    h.number_of_doses,
    h.date_of_first_dose,
    h.date_of_last_dose,
    h.brand_of_vaccine,
    h.brand_of_vaccine_other,
    h.route_of_admission,
    h.route_of_admission_other,
    h.reason_for_vaccination,
    h.total,
    h.suspected,
    h.tested,
    h.confirmed,
    h.admitted,
    h.discharged,
    h.died,
    h.probable,
    h.contact,
    h.load_date
FROM combined_hierarchy h
