{{ config(
    materialized = 'table',
    indexes=[
      {'columns': ['syndrome']},
      {'columns': ['disease']},
      {'columns': ['id']},
      {'columns': ['parent_id']},
      {'columns': ['event_id']},
      {'columns': ['case_date']},
      {'columns': ['epi_week']},
      {'columns': ['type_of_case']},
      {'columns': ['country']},
      {'columns': ['county']},
      {'columns': ['subcounty']},
      {'columns': ['suspected']},
      {'columns': ['tested']},
      {'columns': ['confirmed']},
      {'columns': ['admitted']},
      {'columns': ['discharged']},
      {'columns': ['died']},
      {'columns': ['probable']},
      {'columns': ['contact']},
      {'columns': ['completed']},
    ]
)}}

SELECT 
    id,
    parent_id,
    contact_tree_label,
    mform_id,
    mform_event,
    event_id,
    form_id,
    case_unique_id,
    completed,
    parent_completed,
    created_role,
    modified_role,
    created_username,
    created_timestamp,
    modified_username,
    modified_timestamp,
    location_accuracy,
    location_latitude,
    location_longitude,
    syndrome,
    disease,
    case_date,
    epi_week,
    epid,
    date_of_investigation,
    location_of_investigation,
    location_of_investigation_other,
    CASE WHEN type_of_case IS NOT NULL THEN type_of_case ELSE 'Unknown' END AS type_of_case,
    given_name,
    family_name,
    sex,
    age_years,
    age_months,
    age_days,
    age_group,
    date_of_birth,
    case_is_pregnant,
    phone_number,
    marital_status,
    occupation,
    occupation_other,
    level_of_education,
    case_has_insurance_cover,
    country,
    county,
    subcounty,
    ward,
    town_village_camp,
    landmark,
    title_residence,
    type_of_residence,
    title_parent_guardian,
    guardian_family_name,
    guardian_given_name,
    guardian_phone_number,
    title_respondent,
    respondent,
    respondent_family_name,
    respondent_given_name,
    respondent_address,
    respondent_phone_number,
    respondent_relationship,
    exposure_type_rabies,
    exposure_date,
    exposure_rabies_injury,
    exposure_rabies_injury_site,
    animal_species,
    animal_species_other,
    animal_vaccinated,
    animal_rabies_suspect,
    animal_observed,
    animal_dead,
    animal_dead_days,
    repondent,
    repondent_family_name,
    repondent_given_name,
    repondent_phone_number,
    repondent_address,
    repondent_relationship,
    repondent_relationship_other,
    vaccinated,
    vaccine_name,
    vaccine_doses,
    health_facility,
    vaccination_date,
    case_seen_at_facility,
    date_first_seen_at_facility,
    admitted as case_admitted,
    health_facility_name,
    admission_date,
    inpatient_number,
    discharge_date,
    patient_status,
    (1)::integer AS suspected,
    (CASE WHEN exposure_type_rabies IS NOT NULL THEN 1 ELSE 0 END)::integer AS tested,
    (CASE WHEN type_of_case = 'Confirmed' THEN 1 ELSE 0 END)::integer AS confirmed,
    (CASE WHEN admitted = 'Yes' THEN 1 ELSE 0 END)::integer AS admitted,
    (CASE WHEN patient_status = 'Discharged' THEN 1 ELSE 0 END)::integer AS discharged,
    (CASE WHEN patient_status = 'Dead' THEN 1 ELSE 0 END)::integer AS died,
    (CASE WHEN type_of_case = 'Probable' THEN 1 ELSE 0 END)::integer AS probable,
    (CASE WHEN type_of_case = 'Contact' THEN 1 ELSE 0 END)::integer AS contact,
    current_date AS load_date
FROM {{ ref('int_rabies') }}
