{{ config(
    materialized = 'table',
    indexes=[
      {'columns': ['syndrome']},
      {'columns': ['disease']},
      {'columns': ['case_date']},
      {'columns': ['epi_week']},
      {'columns': ['type_of_case']},
      {'columns': ['country']},
      {'columns': ['county']},
      {'columns': ['subcounty']},
      {'columns': ['suspected']},
      {'columns': ['tested']},
      {'columns': ['confirmed']},
      {'columns': ['admitted']},
      {'columns': ['discharged']},
      {'columns': ['died']},
      {'columns': ['probable']},
      {'columns': ['contact']},
      {'columns': ['completed']},
    ]
)}}

SELECT
    mform_id,
    form_id,
    case_unique_id,
    created_username,
    created_timestamp,
    modified_username,
    modified_timestamp,
    location_accuracy,
    location_latitude,
    location_longitude,
    'Sampling Form for Fortified Foods' AS syndrome,
    'Sampling form for fortified foods' AS disease,
    case_date,
    epi_week,
    epid,
    date_of_investigation,
    location_of_investigation,
    'Unknown'::text AS type_of_case,
    null::text AS sex,
    null::text AS age_group,
    null::text AS country,
    county,
    subcounty,
    ward,
    landmark,
    type_of_premise,
    name_of_premise,
    premise_phone_number,
    premise_email_address,
    sample_number,
    date_of_sample_collection,
    time_of_sample_collection,
    type_of_food_product,
    type_of_food_sample,
    name_of_product,
    description_of_product,
    batch_number,
    date_of_manufacture,
    date_of_expiry,
    name_of_importer_dealer,
    method_of_collection,
    size_of_lot_sample,
    specimen_seal_used,
    reason_for_collection,
    reason_for_collection_other,
    mode_of_sample_delivery,
    date_of_dispatch,
    time_of_dispatch,
    number_of_invoice,
    date_of_invoice,
    shipping_record,
    date_of_shipping,
    other_documents,
    sample_collector_name,
    sample_collector_designation,
    collector_phone_number,
    collectors_email_address,
    (1)::integer AS suspected,
    (CASE WHEN date_of_sample_collection IS NOT NULL THEN 1 ELSE 0 END)::integer AS tested,
    (0)::integer AS confirmed,
    (0)::integer AS admitted,
    (0)::integer AS discharged,
    (0)::integer AS died,
    (0)::integer AS probable,
    (0)::integer AS contact,
    current_date AS load_date,
    ''::text AS completed
FROM {{ ref('int_sampling_form_for_fortified_foods') }}
