{{ config(
    materialized = 'table',
    indexes=[
      {'columns': ['id']},
      {'columns': ['parent_id']},
      {'columns': ['event_id']},
      {'columns': ['case_unique_id']},
      {'columns': ['completed']},
      {'columns': ['parent_completed']},
      {'columns': ['case_date']},
      {'columns': ['epi_week']},
      {'columns': ['name']},
      {'columns': ['contact_is_symptomatic']},
    ]
)}}

SELECT
    id,
    parent_id,
    contact_tree_label,
    mform_id,
    mform_event,
    event_id,
    form_id,
    case_unique_id,
    completed,
    parent_completed,
    created_role,
    modified_role,
    created_username,
    created_timestamp,
    modified_username,
    modified_timestamp,
    location_accuracy,
    location_latitude,
    location_longitude,
    syndrome,
    disease,
    case_date,
    epi_week,
    name,
    age_years,
    sex,
    nationality,
    id_number,
    occupation,
    occupation_other,
    email_address,
    day_of_follow_up,
    date_of_follow_up,
    contact_is_symptomatic
FROM {{ ref('int_mpox_traveler') }}
