{{ config(
    materialized = 'table',
    indexes=[
      {'columns': ['syndrome']},
      {'columns': ['disease']},
      {'columns': ['id']},
      {'columns': ['parent_id']},
      {'columns': ['event_id']},
      {'columns': ['case_date']},
      {'columns': ['epi_week']},
      {'columns': ['country']},
      {'columns': ['county']},
      {'columns': ['subcounty']},
      {'columns': ['total']},
      {'columns': ['suspected']},
      {'columns': ['tested']},
      {'columns': ['confirmed']},
      {'columns': ['admitted']},
      {'columns': ['discharged']},
      {'columns': ['died']},
      {'columns': ['probable']},
      {'columns': ['contact']},
      {'columns': ['completed']},
    ]
)}}

SELECT
    id,
    parent_id,
    contact_tree_label,
    mform_id,
    mform_event,
    event_id,
    form_id,
    case_unique_id,
    completed,
    parent_completed,
    created_role,
    modified_role,
    created_username,
    created_timestamp,
    modified_username,
    modified_timestamp,
    location_accuracy,
    location_latitude,
    location_longitude,
    syndrome,
    'Marburg'::text AS disease,
    '' AS country,
    county,
    '' AS subcounty,
    date_of_assessment,
    case_date,
    epi_week,
    'Unknown' AS type_of_case,
    'Unknown' AS sex,
    'Unknown' AS age_group,
    name_of_the_validator,
    validator_phone_number,
    ipc_staff_trained_vhf_cases,
    ipc_triage_system,
    ipc_hw_trained_80percent,
    ipc_guidelines_sops,
    ipc_community_volunteers_disinfection,
    ipc_teams_household_disinfection,
    ipc_safe_dignified_burial,
    poe_contingency_plan,
    poe_medical_examination_facilities,
    poe_mechanism_temp_monitoring,
    poe_isolation_quarantine_facilities,
    poe_ambulance_service_link,
    poe_integrated_surveillance_system,
    poe_staff_manage_vhf,
    poe_functional_handwashing,
    poe_posters_leaflets,
    rrt_county_trained_multidisciplinary,
    rrt_established_in_highrisk_sc,
    rrt_equipment_logistics_24hr,
    rrt_sops_guidelines,
    wash_prepositioned_kits_80percent,
    wash_80percent_hf_incinerator,
    wash_secure_waste_zones,
    wash_80percent_water_access,
    wash_medical_waste_management,
    overall_comment,
    financing_contingency_emergency_fund,
    lab_pre_positioned_stock,
    lab_reverse_transcriptase_pcr_capacity,
    lab_sops_collection_transport,
    lab_sops_subcounties_80percent,
    lab_staff_trained_sample_transport,
    lab_trained_staff_safety_ipc,
    lab_functional_reporting_system,
    lab_capacity_for_sequencing,
    vaccination_import_clearing_procedures,
    vaccination_strategy_developed,
    vaccination_initiated_80percent_hotspots,
    vaccination_partners_mass_immunisation,
    srv_ph_personnel_idsr_80percent,
    srv_public_health_facilities_reporting,
    srv_community_based_definitions_80percent,
    srv_community_volunteers_training,
    srv_private_health_facilities_vhf,
    srv_risk_assessment_mapping,
    srv_hotspots_list_updated,
    srv_adequate_reporting_tools,
    srv_alert_desks,
    srv_capacity_person_place_time,
    srv_hw_trained_in_ebs,
    cm_guidelines_protocols,
    cm_staff_trained_80percent,
    cm_referral_system_80percent,
    geninfo_total_population,
    geninfo_number_of_subcounties,
    geninfo_high_risk_subcounties,
    geninfo_health_facilities,
    geninfo_hf_in_high_risk_sc,
    geninfo_hcw_in_high_risk_counties,
    geninfo_hw_trained_idsr,
    geninfo_hf_reporting_mvd_idsr,
    geninfo_hf_with_case_defs_mvd,
    geninfo_hf_mvd_investigation_linelisting,
    geninfo_hf_with_cbs_structures,
    geninfo_chv_in_high_risk_communities,
    geninfo_chv_trained_cbs_reporting,
    geninfo_hf_in_high_risk_sc_with_vtm_rdt,
    logproc_case_mgmt_facilities_80percent,
    logproc_hr_isolation_units,
    logproc_essential_stocks_80percent,
    logproc_stock_monitoring_system_80percent,
    logproc_suppliers_list,
    hrh_surge_staff_in_place,
    hrh_clinical_staff_coverage,
    hrh_task_shifting_protocols,
    coord_multisectoral_focal_points,
    coord_multisectoral_mechanism,
    coord_kpis_monitoring_quality_control,
    coord_resource_mobilisation_plan,
    coord_risk_subcounties_multi_sectoral,
    coord_updated_5w_of_partners,
    coord_simulation_exercise,
    rcce_spokespersons_trained,
    rcce_media_partnerships,
    rcce_social_mobilisation_mechanisms,
    rcce_trained_community_volunteers,
    rcce_key_messages_local_languages,
    rcce_platform_engage_community_leaders,
    rcce_existing_chws_in_high_risk,
    rcce_communication_platforms_social,
    rcce_pre_post_outbreak_assessment,
    rcce_national_plan_in_place,
    (1)::integer AS total,
    (0)::integer AS suspected,
    (0)::integer AS tested,
    (0)::integer AS confirmed,
    (0)::integer AS admitted,
    (0)::integer AS discharged,
    (0)::integer AS died,
    (0)::integer AS probable,
    (0)::integer AS contact,
    current_date AS load_date
FROM {{ ref('int_mvd_preparedness') }}
