name: Deploy ADAM training dbt

on:
  schedule:
    - cron: '*/2 * * * *'

env:
  DBT_SERVER_TRAINING: ${{ secrets.DBT_SERVER_TRAINING }}
  DBT_PORT_TRAINING: ${{ secrets.DBT_PORT_TRAINING }}
  DBT_USER_TRAINING: ${{ secrets.DBT_USER_TRAINING }}
  DBT_PASSWORD_TRAINING: ${{ secrets.DBT_PASSWORD_TRAINING }}
  DBT_DATABASE_TRAINING: ${{ secrets.DBT_DATABASE_TRAINING }}
  DBT_SCHEMA: ${{ secrets.DBT_SCHEMA }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-postgres
          dbt deps --profiles-dir ./profiles/ --target training

      - name: Run dbt seeds
        run: |
          dbt seed --profiles-dir ./profiles/ --target training --full-refresh
          
      - name: Run dbt models
        run: |
          dbt run --profiles-dir ./profiles/ --target training

      - name: Run dbt tests
        run: |
          dbt test --profiles-dir ./profiles/ --target training

          
